/* Generated by Nim Compiler v0.17.2 */
/*   (c) 2017 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w  -I/usr/local/Cellar/nim/0.17.2/nim/lib -o /Users/nao/Documents/ray/nim-ray/nimcache/classical.o /Users/nao/Documents/ray/nim-ray/nimcache/classical.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <math.h>
#include <setjmp.h>
#include <stdio.h>
#include <time.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyObject_RaycolonObjectType__LG8JyU20iwDlynW9by9bNTjg tyObject_RaycolonObjectType__LG8JyU20iwDlynW9by9bNTjg;
typedef struct RootObj RootObj;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyObject_SpherecolonObjectType__xgLbzOdh3TOGcRIt0sPK9bw tyObject_SpherecolonObjectType__xgLbzOdh3TOGcRIt0sPK9bw;
typedef struct tyObject_IntersectioncolonObjectType__9a3vySMeWlHTn9cS4C42OloA tyObject_IntersectioncolonObjectType__9a3vySMeWlHTn9cS4C42OloA;
typedef struct tySequence_PcQFOjbvH9cE4G4VxStTXaQ tySequence_PcQFOjbvH9cE4G4VxStTXaQ;
typedef struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack_7fytPA5bBsob6See21YMRA tyObject_GcStack_7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyTuple_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct Exception Exception;
typedef struct TSafePoint TSafePoint;
typedef struct tyObject_TimeInfo_sGezGiKtnmyCJvsDB0xApg tyObject_TimeInfo_sGezGiKtnmyCJvsDB0xApg;
typedef struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ;
typedef NF tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ[3];
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
struct RootObj {
TNimType* m_type;
};
struct tyObject_RaycolonObjectType__LG8JyU20iwDlynW9by9bNTjg {
  RootObj Sup;
tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ origin;
tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ direction;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct tyObject_SpherecolonObjectType__xgLbzOdh3TOGcRIt0sPK9bw {
  RootObj Sup;
NF radius;
tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ position;
};
struct tyObject_IntersectioncolonObjectType__9a3vySMeWlHTn9cS4C42OloA {
  RootObj Sup;
NF distance;
tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ position;
tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ normal;
};
typedef N_NIMCALL_PTR(void, tyProc_T4eqaYlFJYZUv9aG9b1TV0bQ) (void);
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* tyArray_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* tyArray_lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA {
tyArray_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* tyArray_0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
tyArray_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyArray_LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray_LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI lastSize;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* freeChunksList;
tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
};
typedef tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ tyArray_zsqhKd5ZyNb9bqNF9b4zudUw[512];
typedef tyArray_zsqhKd5ZyNb9bqNF9b4zudUw tyArray_tOKM5opUVA8noyk1BIOQpQ[512];
typedef NU8 tyEnum_FileMode_fVUBHvW79bXUw1j55Oo9avSQ;
struct Exception {
  RootObj Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
Exception* up;
};
typedef struct {
N_NIMCALL_PTR(NIM_BOOL, ClP_0) (Exception* e, void* ClE_0);
void* ClE_0;
} tyProc_KeeAOYBd84Ofsw6Y7LizaQ;
struct TSafePoint {
TSafePoint* prev;
NI status;
jmp_buf context;
NIM_BOOL hasRaiseAction;
tyProc_KeeAOYBd84Ofsw6Y7LizaQ raiseAction;
};
typedef NimStringDesc* tyArray_nHXaesL0DJZHyVS07ARPRA[1];
typedef NU8 tyEnum_Month_JS0JuFvCBbC2GL3xXBnPQw;
typedef NU8 tyEnum_WeekDay_SVfemTA9aCOyua2TJYa6yBg;
struct tyObject_TimeInfo_sGezGiKtnmyCJvsDB0xApg {
  RootObj Sup;
NI second;
NI minute;
NI hour;
NI monthday;
tyEnum_Month_JS0JuFvCBbC2GL3xXBnPQw month;
NI year;
tyEnum_WeekDay_SVfemTA9aCOyua2TJYa6yBg weekday;
NI yearday;
NIM_BOOL isDST;
NI timezone;
};
struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w {
NI prevSize;
NI size;
};
struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* next;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* freeList;
NI free;
NI acc;
NF data;
};
struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw {
NI size;
NI acc;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* next;
};
struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* next;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NF data;
};
typedef NI tyArray_9a8QARi5WsUggNU9bom7kzTQ[8];
struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw {
tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg {
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ {
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zeroField;
};
struct tySequence_PcQFOjbvH9cE4G4VxStTXaQ {
  TGenericSeq Sup;
  tyObject_SpherecolonObjectType__xgLbzOdh3TOGcRIt0sPK9bw* data[SEQ_DECL_SIZE];
};
N_NIMCALL(void, vinit_D0k7o2Q7t4kMjeKeSQkHsA)(NF x, NF y, NF z, tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ Result);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(NimStringDesc*, dollar__Jdzsmm9aQG381LH9bG4X6TtQ)(tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ a);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size);
N_NIMCALL(NimStringDesc*, nimFloatToStr)(NF f);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
N_NIMCALL(void, plus__YF7YCu9cPizpHse0BRX79b2w)(tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ left, tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ right, tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ Result);
N_NIMCALL(void, minus__YF7YCu9cPizpHse0BRX79b2w_2)(tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ left, tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ right, tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ Result);
N_NIMCALL(void, star__CcAWkaIqz7U9aP9bTJG9bGtkg)(NF left, tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ right, tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ Result);
N_NIMCALL(void, star__SBIYxhI32AoFv9bOl8Hlakg)(tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ left, NF right, tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ Result);
N_NIMCALL(NF, dot_UN0FaoWT4aScs9cRk3JXL9cg)(tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ left, tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ right);
N_NIMCALL(void, cross_YF7YCu9cPizpHse0BRX79b2w_3)(tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ left, tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ right, tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ Result);
N_NIMCALL(void, mult_YF7YCu9cPizpHse0BRX79b2w_4)(tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ left, tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ right, tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ Result);
N_NIMCALL(NF, norm_agQ9a8BMZlinN0jwv9aAJ3cg)(tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ this_0);
N_NIMCALL(void, normalize_MDc79btIcKT7GafFDU9aTVLA)(tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ this_0, tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ Result);
N_NIMCALL(tyObject_RaycolonObjectType__LG8JyU20iwDlynW9by9bNTjg*, rinit_2tN9c9bGVgB9cwiKTQmw6xNdg)(tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ o, tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ d);
static N_NIMCALL(void, Marker_tyRef_DiBA8cLtLR9bH7Y3ONjjOfg)(void* p, NI op);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_NIMCALL(tyObject_SpherecolonObjectType__xgLbzOdh3TOGcRIt0sPK9bw*, sinit_kI4YLVrvCnubYMh35jX64A)(NF radius, tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ position);
static N_NIMCALL(void, Marker_tyRef_cMwI9aQXCL1qs8LOMk8N9cBg)(void* p, NI op);
N_NIMCALL(tyObject_IntersectioncolonObjectType__9a3vySMeWlHTn9cS4C42OloA*, intersect_8mMOFsZ3yHkWEpNJZVBcdQ)(tyObject_RaycolonObjectType__LG8JyU20iwDlynW9by9bNTjg* r, tyObject_SpherecolonObjectType__xgLbzOdh3TOGcRIt0sPK9bw* sphere);
N_NOINLINE(void, chckNil)(void* p);
static N_NIMCALL(void, Marker_tyRef_pz9bTTOY0l9ckLJHmqRuTH0w)(void* p, NI op);
N_NIMCALL(NF, clamp_mRMGCrjhFi6lcd8r0rTqPA)(NF x);
N_NIMCALL(NI, toInt_glNdNQuZoVn2fP9bTsL9ckOw)(NF x);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, Marker_tySequence_PcQFOjbvH9cE4G4VxStTXaQ)(void* p, NI op);
static N_NIMCALL(void, TM_YJO1YzEYGZ9aXsNuQl5zaUw_8)(void);
N_NIMCALL(void, nimRegisterGlobalMarker)(tyProc_T4eqaYlFJYZUv9aG9b1TV0bQ markerProc);
static N_INLINE(void, nimGCunrefRC1)(void* p);
static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
N_NIMCALL(void*, newSeqRC1)(TNimType* typ, NI len);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
N_NIMCALL(void, genericReset)(void* dest, TNimType* mt);
static N_INLINE(NF, slash__fu0hCFNNw3xnGgcs2KwTWgsystem)(NI x, NI y);
N_NIMCALL(NI, mulInt)(NI a, NI b);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_NIMCALL(void, TM_YJO1YzEYGZ9aXsNuQl5zaUw_13)(void);
static N_NIMCALL(void, TM_YJO1YzEYGZ9aXsNuQl5zaUw_14)(void);
static N_NIMCALL(void, TM_YJO1YzEYGZ9aXsNuQl5zaUw_15)(void);
N_NOINLINE(void, raiseIndexError)(void);
static N_NIMCALL(void, TM_YJO1YzEYGZ9aXsNuQl5zaUw_16)(void);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NIMCALL(void, failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA)(NimStringDesc* msg);
N_NIMCALL(void, ppmFileWrite_n3DR45ExtAtzSFu9amJ8c5g)(NimStringDesc* fileName, tyArray_tOKM5opUVA8noyk1BIOQpQ img);
N_NIMCALL(FILE*, open_hqzpWQbdA2B8l9a6wwNoP4g)(NimStringDesc* filename, tyEnum_FileMode_fVUBHvW79bXUw1j55Oo9avSQ mode, NI bufSize);
static N_INLINE(void, pushSafePoint)(TSafePoint* s);
static N_INLINE(void, writeLine_rBQVO3cm3BhnA9aEFD7PG6Qclassical)(FILE* f, NimStringDesc** x, NI xLen_0);
N_NIMCALL(void, write_c4mGyJBvK73pdM22jiweKQ)(FILE* f, NimStringDesc* s);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x);
static N_INLINE(void, popSafePoint)(void);
static N_INLINE(void, setFrame)(TFrame* s);
N_NIMCALL(void, close_BWnr8V7RERYno9bIdPmw8Hw_2)(FILE* f);
N_NIMCALL(void, reraiseException)(void);
N_NIMCALL(NimStringDesc*, format_yA59a7f0M79aw68UsupvAfRA)(tyObject_TimeInfo_sGezGiKtnmyCJvsDB0xApg* info, NimStringDesc* f);
N_NIMCALL(void, getLocalTime_Ql5lAb5s0QPmy9b8QhS3ucg_2)(time_t t, tyObject_TimeInfo_sGezGiKtnmyCJvsDB0xApg* Result);
N_NIMCALL(time_t, getTime_Ft5FFURWITtb9aR6Hjpq6UQ)(void);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* theStackBottom);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void);
NIM_EXTERNC N_NOINLINE(void, classicalDatInit000)(void);
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TNimType NTI_13RNkKqUOX1TtorOUlKtqA_;
TNimType NTI_LG8JyU20iwDlynW9by9bNTjg_;
extern TNimType NTI_w9bl9a1ul9ctRJWiMl9cNnIMvg_;
TNimType NTI_9ce69c9a1NzlPVqY9aKHS79b5IQ_;
TNimType NTI_DiBA8cLtLR9bH7Y3ONjjOfg_;
TNimType NTI_xgLbzOdh3TOGcRIt0sPK9bw_;
TNimType NTI_cMwI9aQXCL1qs8LOMk8N9cBg_;
TNimType NTI_9a3vySMeWlHTn9cS4C42OloA_;
TNimType NTI_pz9bTTOY0l9ckLJHmqRuTH0w_;
tySequence_PcQFOjbvH9cE4G4VxStTXaQ* spheres_kh1Yb53gCvZuGB9cEty7Ixw;
TNimType NTI_PcQFOjbvH9cE4G4VxStTXaQ_;
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
tyArray_tOKM5opUVA8noyk1BIOQpQ img_kzpomObqN8W7DgE3OGgP9cw;
NI x_Bm3EbA5a9a9ae3uTNftAm1aw;
NI y_3BnVL7bQV7oWgWI8lHQ9cnA;
tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ o_1PRQa9bVBwRgYsdCVXZEHdw;
tyObject_RaycolonObjectType__LG8JyU20iwDlynW9by9bNTjg* ray_KN4t3FfPCNhMHU1EQvoM9cw;
tyObject_IntersectioncolonObjectType__9a3vySMeWlHTn9cS4C42OloA* near_gRNrQG3q6ISClYgsw4cwmQ;
tyObject_SpherecolonObjectType__xgLbzOdh3TOGcRIt0sPK9bw* sphere_TwHbp9bLlawSqh9bEjXlztmg;
tyObject_IntersectioncolonObjectType__9a3vySMeWlHTn9cS4C42OloA* intersection_l44uuhk7TH2yIMpMMOPJWg;
extern TSafePoint* excHandler_rqLlY5bs9atDw2OXYqJEn5g;
extern TNimType NTI_sGezGiKtnmyCJvsDB0xApg_;
STRING_LITERAL(TM_YJO1YzEYGZ9aXsNuQl5zaUw_2, "[", 1);
STRING_LITERAL(TM_YJO1YzEYGZ9aXsNuQl5zaUw_3, ", ", 2);
STRING_LITERAL(TM_YJO1YzEYGZ9aXsNuQl5zaUw_4, "]", 1);
STRING_LITERAL(TM_YJO1YzEYGZ9aXsNuQl5zaUw_18, "len(a) == L seq modified while iterating over it", 48);
STRING_LITERAL(TM_YJO1YzEYGZ9aXsNuQl5zaUw_21, "img/", 4);
STRING_LITERAL(TM_YJO1YzEYGZ9aXsNuQl5zaUw_23, "\012", 1);
STRING_LITERAL(TM_YJO1YzEYGZ9aXsNuQl5zaUw_25, "P3", 2);
NIM_CONST tyArray_nHXaesL0DJZHyVS07ARPRA TM_YJO1YzEYGZ9aXsNuQl5zaUw_24 = {((NimStringDesc*) &TM_YJO1YzEYGZ9aXsNuQl5zaUw_25)}
;
STRING_LITERAL(TM_YJO1YzEYGZ9aXsNuQl5zaUw_26, "# The P3 means colors are in ASCII, then ", 41);
STRING_LITERAL(TM_YJO1YzEYGZ9aXsNuQl5zaUw_27, " columns and ", 13);
STRING_LITERAL(TM_YJO1YzEYGZ9aXsNuQl5zaUw_28, " rows, then 255 for max color, then RGB triplets", 48);
STRING_LITERAL(TM_YJO1YzEYGZ9aXsNuQl5zaUw_29, " ", 1);
STRING_LITERAL(TM_YJO1YzEYGZ9aXsNuQl5zaUw_31, "255", 3);
NIM_CONST tyArray_nHXaesL0DJZHyVS07ARPRA TM_YJO1YzEYGZ9aXsNuQl5zaUw_30 = {((NimStringDesc*) &TM_YJO1YzEYGZ9aXsNuQl5zaUw_31)}
;
STRING_LITERAL(TM_YJO1YzEYGZ9aXsNuQl5zaUw_34, "done", 4);
STRING_LITERAL(TM_YJO1YzEYGZ9aXsNuQl5zaUw_35, "img", 3);
STRING_LITERAL(TM_YJO1YzEYGZ9aXsNuQl5zaUw_36, "yyyyMMdd-HHmmss", 15);
STRING_LITERAL(TM_YJO1YzEYGZ9aXsNuQl5zaUw_37, ".ppm", 4);

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_NIMCALL(void, vinit_D0k7o2Q7t4kMjeKeSQkHsA)(NF x, NF y, NF z, tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ Result) {
	nimfr_("vinit", "vector3.nim");
	nimln_(8, "vector3.nim");
	Result[0] = x;
	Result[1] = y;
	Result[2] = z;
	popFrame();
}

static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	copyMem_E1xtACub5WcDa3vbrIXbwgsystem(((void*) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
	(*dest).Sup.len += (*src).Sup.len;
}

N_NIMCALL(NimStringDesc*, dollar__Jdzsmm9aQG381LH9bG4X6TtQ)(tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ a) {
	NimStringDesc* result;
	NimStringDesc* T1_;
	NimStringDesc* T2_;
	NimStringDesc* T3_;
	NimStringDesc* T4_;
	nimfr_("$", "vector3.nim");
	result = (NimStringDesc*)0;
	nimln_(11, "vector3.nim");
	T1_ = (NimStringDesc*)0;
	T2_ = (NimStringDesc*)0;
	T2_ = nimFloatToStr(a[(((NI) 0))- 0]);
	T3_ = (NimStringDesc*)0;
	T3_ = nimFloatToStr(a[(((NI) 1))- 0]);
	T4_ = (NimStringDesc*)0;
	T4_ = nimFloatToStr(a[(((NI) 2))- 0]);
	T1_ = rawNewString(T2_->Sup.len + T3_->Sup.len + T4_->Sup.len + 6);
appendString(T1_, ((NimStringDesc*) &TM_YJO1YzEYGZ9aXsNuQl5zaUw_2));
appendString(T1_, T2_);
appendString(T1_, ((NimStringDesc*) &TM_YJO1YzEYGZ9aXsNuQl5zaUw_3));
appendString(T1_, T3_);
appendString(T1_, ((NimStringDesc*) &TM_YJO1YzEYGZ9aXsNuQl5zaUw_3));
appendString(T1_, T4_);
appendString(T1_, ((NimStringDesc*) &TM_YJO1YzEYGZ9aXsNuQl5zaUw_4));
	result = T1_;
	popFrame();
	return result;
}

N_NIMCALL(void, plus__YF7YCu9cPizpHse0BRX79b2w)(tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ left, tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ right, tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ Result) {
	nimfr_("+", "vector3.nim");
	nimln_(14, "vector3.nim");
	Result[0] = ((NF)(left[(((NI) 0))- 0]) + (NF)(right[(((NI) 0))- 0]));
	Result[1] = ((NF)(left[(((NI) 1))- 0]) + (NF)(right[(((NI) 1))- 0]));
	Result[2] = ((NF)(left[(((NI) 2))- 0]) + (NF)(right[(((NI) 2))- 0]));
	popFrame();
}

N_NIMCALL(void, minus__YF7YCu9cPizpHse0BRX79b2w_2)(tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ left, tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ right, tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ Result) {
	nimfr_("-", "vector3.nim");
	nimln_(17, "vector3.nim");
	Result[0] = ((NF)(left[(((NI) 0))- 0]) - (NF)(right[(((NI) 0))- 0]));
	Result[1] = ((NF)(left[(((NI) 1))- 0]) - (NF)(right[(((NI) 1))- 0]));
	Result[2] = ((NF)(left[(((NI) 2))- 0]) - (NF)(right[(((NI) 2))- 0]));
	popFrame();
}

N_NIMCALL(void, star__CcAWkaIqz7U9aP9bTJG9bGtkg)(NF left, tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ right, tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ Result) {
	nimfr_("*", "vector3.nim");
	nimln_(20, "vector3.nim");
	Result[0] = ((NF)(left) * (NF)(right[(((NI) 0))- 0]));
	Result[1] = ((NF)(left) * (NF)(right[(((NI) 1))- 0]));
	Result[2] = ((NF)(left) * (NF)(right[(((NI) 2))- 0]));
	popFrame();
}

N_NIMCALL(void, star__SBIYxhI32AoFv9bOl8Hlakg)(tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ left, NF right, tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ Result) {
	nimfr_("*", "vector3.nim");
	nimln_(23, "vector3.nim");
	Result[0] = ((NF)(left[(((NI) 0))- 0]) * (NF)(right));
	Result[1] = ((NF)(left[(((NI) 1))- 0]) * (NF)(right));
	Result[2] = ((NF)(left[(((NI) 2))- 0]) * (NF)(right));
	popFrame();
}

N_NIMCALL(NF, dot_UN0FaoWT4aScs9cRk3JXL9cg)(tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ left, tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ right) {
	NF result;
	nimfr_("dot", "vector3.nim");
	result = (NF)0;
	nimln_(26, "vector3.nim");
	result = ((NF)(((NF)(((NF)(left[(((NI) 0))- 0]) * (NF)(right[(((NI) 0))- 0]))) + (NF)(((NF)(left[(((NI) 1))- 0]) * (NF)(right[(((NI) 1))- 0]))))) + (NF)(((NF)(left[(((NI) 2))- 0]) * (NF)(right[(((NI) 2))- 0]))));
	popFrame();
	return result;
}

N_NIMCALL(void, cross_YF7YCu9cPizpHse0BRX79b2w_3)(tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ left, tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ right, tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ Result) {
	nimfr_("cross", "vector3.nim");
	nimln_(29, "vector3.nim");
	Result[0] = ((NF)(((NF)(left[(((NI) 1))- 0]) * (NF)(right[(((NI) 2))- 0]))) - (NF)(((NF)(right[(((NI) 2))- 0]) * (NF)(left[(((NI) 1))- 0]))));
	Result[1] = ((NF)(((NF)(left[(((NI) 2))- 0]) * (NF)(right[(((NI) 0))- 0]))) - (NF)(((NF)(right[(((NI) 0))- 0]) * (NF)(left[(((NI) 2))- 0]))));
	Result[2] = ((NF)(((NF)(left[(((NI) 0))- 0]) * (NF)(right[(((NI) 1))- 0]))) - (NF)(((NF)(right[(((NI) 1))- 0]) * (NF)(left[(((NI) 0))- 0]))));
	popFrame();
}

N_NIMCALL(void, mult_YF7YCu9cPizpHse0BRX79b2w_4)(tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ left, tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ right, tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ Result) {
	nimfr_("mult", "vector3.nim");
	nimln_(32, "vector3.nim");
	Result[0] = ((NF)(left[(((NI) 0))- 0]) * (NF)(right[(((NI) 0))- 0]));
	Result[1] = ((NF)(left[(((NI) 1))- 0]) * (NF)(right[(((NI) 1))- 0]));
	Result[2] = ((NF)(left[(((NI) 2))- 0]) * (NF)(right[(((NI) 2))- 0]));
	popFrame();
}

N_NIMCALL(NF, norm_agQ9a8BMZlinN0jwv9aAJ3cg)(tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ this_0) {
	NF result;
	NF T1_;
	nimfr_("norm", "vector3.nim");
	result = (NF)0;
	nimln_(35, "vector3.nim");
	T1_ = (NF)0;
	T1_ = dot_UN0FaoWT4aScs9cRk3JXL9cg(this_0, this_0);
	result = sqrt(T1_);
	popFrame();
	return result;
}

N_NIMCALL(void, normalize_MDc79btIcKT7GafFDU9aTVLA)(tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ this_0, tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ Result) {
	NF T1_;
	tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ T2_;
	nimfr_("normalize", "vector3.nim");
	nimln_(38, "vector3.nim");
	T1_ = (NF)0;
	T1_ = norm_agQ9a8BMZlinN0jwv9aAJ3cg(this_0);
	memset((void*)T2_, 0, sizeof(T2_));
	star__SBIYxhI32AoFv9bOl8Hlakg(this_0, ((NF)(1.0000000000000000e+00) / (NF)(T1_)), T2_);
	memcpy((void*)Result, (NIM_CONST void*)T2_, sizeof(tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ));
	popFrame();
}
static N_NIMCALL(void, Marker_tyRef_DiBA8cLtLR9bH7Y3ONjjOfg)(void* p, NI op) {
	tyObject_RaycolonObjectType__LG8JyU20iwDlynW9by9bNTjg* a;
	NI T1_;
	NI T2_;
	a = (tyObject_RaycolonObjectType__LG8JyU20iwDlynW9by9bNTjg*)p;
	T1_ = (NI)0;
	T2_ = (NI)0;
}

N_NIMCALL(tyObject_RaycolonObjectType__LG8JyU20iwDlynW9by9bNTjg*, rinit_2tN9c9bGVgB9cwiKTQmw6xNdg)(tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ o, tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ d) {
	tyObject_RaycolonObjectType__LG8JyU20iwDlynW9by9bNTjg* result;
	tyObject_RaycolonObjectType__LG8JyU20iwDlynW9by9bNTjg* T1_;
	nimfr_("rinit", "ray.nim");
	result = (tyObject_RaycolonObjectType__LG8JyU20iwDlynW9by9bNTjg*)0;
	nimln_(7, "ray.nim");
	T1_ = (tyObject_RaycolonObjectType__LG8JyU20iwDlynW9by9bNTjg*)0;
	T1_ = (tyObject_RaycolonObjectType__LG8JyU20iwDlynW9by9bNTjg*) newObj((&NTI_DiBA8cLtLR9bH7Y3ONjjOfg_), sizeof(tyObject_RaycolonObjectType__LG8JyU20iwDlynW9by9bNTjg));
	(*T1_).Sup.m_type = (&NTI_LG8JyU20iwDlynW9by9bNTjg_);
	memcpy((void*)(*T1_).origin, (NIM_CONST void*)o, sizeof(tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ));
	memcpy((void*)(*T1_).direction, (NIM_CONST void*)d, sizeof(tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ));
	result = T1_;
	popFrame();
	return result;
}
static N_NIMCALL(void, Marker_tyRef_cMwI9aQXCL1qs8LOMk8N9cBg)(void* p, NI op) {
	tyObject_SpherecolonObjectType__xgLbzOdh3TOGcRIt0sPK9bw* a;
	NI T1_;
	a = (tyObject_SpherecolonObjectType__xgLbzOdh3TOGcRIt0sPK9bw*)p;
	T1_ = (NI)0;
}

N_NIMCALL(tyObject_SpherecolonObjectType__xgLbzOdh3TOGcRIt0sPK9bw*, sinit_kI4YLVrvCnubYMh35jX64A)(NF radius, tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ position) {
	tyObject_SpherecolonObjectType__xgLbzOdh3TOGcRIt0sPK9bw* result;
	tyObject_SpherecolonObjectType__xgLbzOdh3TOGcRIt0sPK9bw* T1_;
	nimfr_("sinit", "sphere.nim");
	result = (tyObject_SpherecolonObjectType__xgLbzOdh3TOGcRIt0sPK9bw*)0;
	nimln_(10, "sphere.nim");
	T1_ = (tyObject_SpherecolonObjectType__xgLbzOdh3TOGcRIt0sPK9bw*)0;
	T1_ = (tyObject_SpherecolonObjectType__xgLbzOdh3TOGcRIt0sPK9bw*) newObj((&NTI_cMwI9aQXCL1qs8LOMk8N9cBg_), sizeof(tyObject_SpherecolonObjectType__xgLbzOdh3TOGcRIt0sPK9bw));
	(*T1_).Sup.m_type = (&NTI_xgLbzOdh3TOGcRIt0sPK9bw_);
	(*T1_).radius = radius;
	memcpy((void*)(*T1_).position, (NIM_CONST void*)position, sizeof(tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ));
	result = T1_;
	popFrame();
	return result;
}
static N_NIMCALL(void, Marker_tyRef_pz9bTTOY0l9ckLJHmqRuTH0w)(void* p, NI op) {
	tyObject_IntersectioncolonObjectType__9a3vySMeWlHTn9cS4C42OloA* a;
	NI T1_;
	NI T2_;
	a = (tyObject_IntersectioncolonObjectType__9a3vySMeWlHTn9cS4C42OloA*)p;
	T1_ = (NI)0;
	T2_ = (NI)0;
}

N_NIMCALL(tyObject_IntersectioncolonObjectType__9a3vySMeWlHTn9cS4C42OloA*, intersect_8mMOFsZ3yHkWEpNJZVBcdQ)(tyObject_RaycolonObjectType__LG8JyU20iwDlynW9by9bNTjg* r, tyObject_SpherecolonObjectType__xgLbzOdh3TOGcRIt0sPK9bw* sphere) {
	tyObject_IntersectioncolonObjectType__9a3vySMeWlHTn9cS4C42OloA* result;
	tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ po;
	tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ T1_;
	NF det;
	NF T2_;
	NF T3_;
	NF T4_;
	NF T5_;
	NF EPS;
	NF tminus;
	NF T10_;
	NF T11_;
	NF tplus;
	NF T12_;
	NF T13_;
	NF distance;
	tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ position;
	tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ T25_;
	tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ T26_;
	tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ normal;
	tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ T27_;
	tyObject_IntersectioncolonObjectType__9a3vySMeWlHTn9cS4C42OloA* T28_;
	nimfr_("intersect", "sphere.nim");
{	result = (tyObject_IntersectioncolonObjectType__9a3vySMeWlHTn9cS4C42OloA*)0;
	memset((void*)po, 0, sizeof(po));
	nimln_(20, "sphere.nim");
	memset((void*)T1_, 0, sizeof(T1_));
	minus__YF7YCu9cPizpHse0BRX79b2w_2((*r).origin, (*sphere).position, T1_);
	memcpy((void*)po, (NIM_CONST void*)T1_, sizeof(tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ));
	nimln_(21, "sphere.nim");
	T2_ = (NF)0;
	T2_ = dot_UN0FaoWT4aScs9cRk3JXL9cg((*r).direction, po);
	T3_ = (NF)0;
	T3_ = pow(T2_, 2.0000000000000000e+00);
	T4_ = (NF)0;
	T4_ = dot_UN0FaoWT4aScs9cRk3JXL9cg(po, po);
	T5_ = (NF)0;
	T5_ = pow((*sphere).radius, 2.0000000000000000e+00);
	det = ((NF)(((NF)(T3_) - (NF)(T4_))) + (NF)(T5_));
	nimln_(22, "sphere.nim");
	EPS = 1.0000000000000000e-10;
	nimln_(23, "sphere.nim");
	{
		if (!(det < 0.0)) goto LA8_;
		nimln_(24, "sphere.nim");
		result = NIM_NIL;
		goto BeforeRet_;
	}
	LA8_: ;
	nimln_(26, "sphere.nim");
	T10_ = (NF)0;
	T10_ = dot_UN0FaoWT4aScs9cRk3JXL9cg((*r).direction, po);
	T11_ = (NF)0;
	T11_ = sqrt(det);
	tminus = ((NF)(-(T10_)) - (NF)(T11_));
	nimln_(27, "sphere.nim");
	T12_ = (NF)0;
	T12_ = dot_UN0FaoWT4aScs9cRk3JXL9cg((*r).direction, po);
	T13_ = (NF)0;
	T13_ = sqrt(det);
	tplus = ((NF)(-(T12_)) + (NF)(T13_));
	nimln_(28, "sphere.nim");
	{
		NIM_BOOL T16_;
		T16_ = (NIM_BOOL)0;
		T16_ = (tminus < EPS);
		if (!(T16_)) goto LA17_;
		T16_ = (tplus < EPS);
		LA17_: ;
		if (!T16_) goto LA18_;
		nimln_(29, "sphere.nim");
		result = NIM_NIL;
		goto BeforeRet_;
	}
	LA18_: ;
	nimln_(30, "sphere.nim");
	{
		if (!(tminus < 0.0)) goto LA22_;
		distance = tplus;
	}
	goto LA20_;
	LA22_: ;
	{
		distance = tminus;
	}
	LA20_: ;
	memset((void*)position, 0, sizeof(position));
	nimln_(33, "sphere.nim");
	memset((void*)T25_, 0, sizeof(T25_));
	star__CcAWkaIqz7U9aP9bTJG9bGtkg(distance, (*r).direction, T25_);
	memset((void*)T26_, 0, sizeof(T26_));
	plus__YF7YCu9cPizpHse0BRX79b2w((*r).origin, T25_, T26_);
	memcpy((void*)position, (NIM_CONST void*)T26_, sizeof(tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ));
	memset((void*)normal, 0, sizeof(normal));
	nimln_(34, "sphere.nim");
	memset((void*)T27_, 0, sizeof(T27_));
	minus__YF7YCu9cPizpHse0BRX79b2w_2(position, (*sphere).position, T27_);
	chckNil((void*)normal);
	memset((void*)normal, 0, sizeof(normal));
	normalize_MDc79btIcKT7GafFDU9aTVLA(T27_, normal);
	nimln_(35, "sphere.nim");
	T28_ = (tyObject_IntersectioncolonObjectType__9a3vySMeWlHTn9cS4C42OloA*)0;
	T28_ = (tyObject_IntersectioncolonObjectType__9a3vySMeWlHTn9cS4C42OloA*) newObj((&NTI_pz9bTTOY0l9ckLJHmqRuTH0w_), sizeof(tyObject_IntersectioncolonObjectType__9a3vySMeWlHTn9cS4C42OloA));
	(*T28_).Sup.m_type = (&NTI_9a3vySMeWlHTn9cS4C42OloA_);
	(*T28_).distance = distance;
	memcpy((void*)(*T28_).position, (NIM_CONST void*)position, sizeof(tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ));
	memcpy((void*)(*T28_).normal, (NIM_CONST void*)normal, sizeof(tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ));
	result = T28_;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_NIMCALL(NF, clamp_mRMGCrjhFi6lcd8r0rTqPA)(NF x) {
	NF result;
	nimfr_("clamp", "filewrite.nim");
	result = (NF)0;
	nimln_(3, "filewrite.nim");
	{
		if (!(x < 0.0)) goto LA3_;
		result = 0.0;
	}
	goto LA1_;
	LA3_: ;
	{
		nimln_(5, "filewrite.nim");
		if (!(1.0000000000000000e+00 < x)) goto LA6_;
		result = 1.0000000000000000e+00;
	}
	goto LA1_;
	LA6_: ;
	{
		result = x;
	}
	LA1_: ;
	popFrame();
	return result;
}

N_NIMCALL(NI, toInt_glNdNQuZoVn2fP9bTsL9ckOw)(NF x) {
	NI result;
	NF T1_;
	nimfr_("toInt", "filewrite.nim");
	result = (NI)0;
	nimln_(11, "filewrite.nim");
	T1_ = (NF)0;
	T1_ = clamp_mRMGCrjhFi6lcd8r0rTqPA(x);
	result = ((NI) (((NF)(T1_) * (NF)(2.5500000000000000e+02))));
	popFrame();
	return result;
}
static N_NIMCALL(void, Marker_tySequence_PcQFOjbvH9cE4G4VxStTXaQ)(void* p, NI op) {
	tySequence_PcQFOjbvH9cE4G4VxStTXaQ* a;
	NI T1_;
	a = (tySequence_PcQFOjbvH9cE4G4VxStTXaQ*)p;
	T1_ = (NI)0;
	for (T1_ = 0; T1_ < a->Sup.len; T1_++) {
	nimGCvisit((void*)a->data[T1_], op);
	}
}
static N_NIMCALL(void, TM_YJO1YzEYGZ9aXsNuQl5zaUw_8)(void) {
	nimGCvisit((void*)spheres_kh1Yb53gCvZuGB9cEty7Ixw, 0);
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("rtlAddZCT", "gc.nim");
	nimln_(216, "gc.nim");
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
	popFrame();
}

static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("decRef", "gc.nim");
	nimln_(223, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(224, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}

static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	nimfr_("usrToCell", "gc.nim");
	result = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln_(138, "gc.nim");
	result = ((tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	popFrame();
	return result;
}

static N_INLINE(void, nimGCunrefRC1)(void* p) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T1_;
	nimfr_("nimGCunrefRC1", "gc.nim");
	nimln_(263, "gc.nim");
	T1_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	T1_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(p);
	decRef_MV4BBk6J1qu70IbBxwEn4wsystem(T1_);
	popFrame();
}

static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("incRef", "gc.nim");
	nimln_(196, "gc.nim");
	(*c).refcount = (NI)((NU64)((*c).refcount) + (NU64)(((NI) 8)));
	popFrame();
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	nimfr_("asgnRef", "gc.nim");
	nimln_(269, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T5_;
		nimln_(378, "system.nim");
		nimln_(269, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3_;
		T5_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T5_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		incRef_9cAA5YuQAAC3MVbnGeV86swsystem(T5_);
	}
	LA3_: ;
	nimln_(270, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T10_;
		nimln_(378, "system.nim");
		nimln_(270, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA8_;
		T10_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T10_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		decRef_MV4BBk6J1qu70IbBxwEn4wsystem(T10_);
	}
	LA8_: ;
	nimln_(271, "gc.nim");
	(*dest) = src;
	popFrame();
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (a <= i);
		if (!(T3_)) goto LA4_;
		T3_ = (i <= b);
		LA4_: ;
		if (!T3_) goto LA5_;
		result = i;
		goto BeforeRet_;
	}
	goto LA1_;
	LA5_: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NF, slash__fu0hCFNNw3xnGgcs2KwTWgsystem)(NI x, NI y) {
	NF result;
	nimfr_("/", "system.nim");
	result = (NF)0;
	nimln_(3384, "system.nim");
	result = ((NF)(((double) (x))) / (NF)(((double) (y))));
	popFrame();
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}
static N_NIMCALL(void, TM_YJO1YzEYGZ9aXsNuQl5zaUw_13)(void) {
	nimGCvisit((void*)ray_KN4t3FfPCNhMHU1EQvoM9cw, 0);
}
static N_NIMCALL(void, TM_YJO1YzEYGZ9aXsNuQl5zaUw_14)(void) {
	nimGCvisit((void*)near_gRNrQG3q6ISClYgsw4cwmQ, 0);
}
static N_NIMCALL(void, TM_YJO1YzEYGZ9aXsNuQl5zaUw_15)(void) {
	nimGCvisit((void*)sphere_TwHbp9bLlawSqh9bEjXlztmg, 0);
}
static N_NIMCALL(void, TM_YJO1YzEYGZ9aXsNuQl5zaUw_16)(void) {
	nimGCvisit((void*)intersection_l44uuhk7TH2yIMpMMOPJWg, 0);
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void, pushSafePoint)(TSafePoint* s) {
	(*s).hasRaiseAction = NIM_FALSE;
	(*s).prev = excHandler_rqLlY5bs9atDw2OXYqJEn5g;
	excHandler_rqLlY5bs9atDw2OXYqJEn5g = s;
}

static N_INLINE(void, writeLine_rBQVO3cm3BhnA9aEFD7PG6Qclassical)(FILE* f, NimStringDesc** x, NI xLen_0) {
	nimfr_("writeLine", "sysio.nim");
	{
		NimStringDesc* i;
		NI i_2;
		i = (NimStringDesc*)0;
		nimln_(2078, "system.nim");
		i_2 = ((NI) 0);
		{
			nimln_(2079, "system.nim");
			while (1) {
				if (!(i_2 < xLen_0)) goto LA3;
				nimln_(2080, "system.nim");
				i = x[i_2];
				nimln_(259, "sysio.nim");
				write_c4mGyJBvK73pdM22jiweKQ(f, i);
				nimln_(2081, "system.nim");
				i_2 += ((NI) 1);
			} LA3: ;
		}
	}
	nimln_(260, "sysio.nim");
	write_c4mGyJBvK73pdM22jiweKQ(f, ((NimStringDesc*) &TM_YJO1YzEYGZ9aXsNuQl5zaUw_23));
	popFrame();
}

static N_INLINE(void, popSafePoint)(void) {
	excHandler_rqLlY5bs9atDw2OXYqJEn5g = (*excHandler_rqLlY5bs9atDw2OXYqJEn5g).prev;
}

static N_INLINE(void, setFrame)(TFrame* s) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
}

N_NIMCALL(void, ppmFileWrite_n3DR45ExtAtzSFu9amJ8c5g)(NimStringDesc* fileName, tyArray_tOKM5opUVA8noyk1BIOQpQ img) {
	FILE* f;
	NimStringDesc* T1_;
	NI width;
	NI height;
	TSafePoint TM_YJO1YzEYGZ9aXsNuQl5zaUw_22;
	nimfr_("ppmFileWrite", "filewrite.nim");
	nimln_(16, "filewrite.nim");
	T1_ = (NimStringDesc*)0;
	T1_ = rawNewString(fileName->Sup.len + 4);
appendString(T1_, ((NimStringDesc*) &TM_YJO1YzEYGZ9aXsNuQl5zaUw_21));
appendString(T1_, fileName);
	f = open_hqzpWQbdA2B8l9a6wwNoP4g(T1_, ((tyEnum_FileMode_fVUBHvW79bXUw1j55Oo9avSQ) 1), ((NI) -1));
	nimln_(17, "filewrite.nim");
	width = ((NI) 512);
	nimln_(18, "filewrite.nim");
	height = ((NI) 512);
	nimln_(19, "filewrite.nim");
	pushSafePoint(&TM_YJO1YzEYGZ9aXsNuQl5zaUw_22);
	TM_YJO1YzEYGZ9aXsNuQl5zaUw_22.status = _setjmp(TM_YJO1YzEYGZ9aXsNuQl5zaUw_22.context);
	if (TM_YJO1YzEYGZ9aXsNuQl5zaUw_22.status == 0) {
		tyArray_nHXaesL0DJZHyVS07ARPRA T3_;
		NimStringDesc* T4_;
		NimStringDesc* T5_;
		NimStringDesc* T6_;
		tyArray_nHXaesL0DJZHyVS07ARPRA T7_;
		NimStringDesc* T8_;
		NimStringDesc* T9_;
		NimStringDesc* T10_;
		nimln_(22, "filewrite.nim");
		writeLine_rBQVO3cm3BhnA9aEFD7PG6Qclassical(f, TM_YJO1YzEYGZ9aXsNuQl5zaUw_24, 1);
		nimln_(23, "filewrite.nim");
		memset((void*)T3_, 0, sizeof(T3_));
		T4_ = (NimStringDesc*)0;
		T5_ = (NimStringDesc*)0;
		T5_ = nimIntToStr(width);
		T6_ = (NimStringDesc*)0;
		T6_ = nimIntToStr(height);
		T4_ = rawNewString(T5_->Sup.len + T6_->Sup.len + 102);
appendString(T4_, ((NimStringDesc*) &TM_YJO1YzEYGZ9aXsNuQl5zaUw_26));
appendString(T4_, T5_);
appendString(T4_, ((NimStringDesc*) &TM_YJO1YzEYGZ9aXsNuQl5zaUw_27));
appendString(T4_, T6_);
appendString(T4_, ((NimStringDesc*) &TM_YJO1YzEYGZ9aXsNuQl5zaUw_28));
		T3_[0] = T4_;
		writeLine_rBQVO3cm3BhnA9aEFD7PG6Qclassical(f, T3_, 1);
		nimln_(24, "filewrite.nim");
		memset((void*)T7_, 0, sizeof(T7_));
		T8_ = (NimStringDesc*)0;
		T9_ = (NimStringDesc*)0;
		T9_ = nimIntToStr(width);
		T10_ = (NimStringDesc*)0;
		T10_ = nimIntToStr(height);
		T8_ = rawNewString(T9_->Sup.len + T10_->Sup.len + 1);
appendString(T8_, T9_);
appendString(T8_, ((NimStringDesc*) &TM_YJO1YzEYGZ9aXsNuQl5zaUw_29));
appendString(T8_, T10_);
		T7_[0] = T8_;
		writeLine_rBQVO3cm3BhnA9aEFD7PG6Qclassical(f, T7_, 1);
		nimln_(25, "filewrite.nim");
		writeLine_rBQVO3cm3BhnA9aEFD7PG6Qclassical(f, TM_YJO1YzEYGZ9aXsNuQl5zaUw_30, 1);
		{
			NI y;
			NI volatile res;
			y = (NI)0;
			nimln_(1986, "system.nim");
			res = ((NI) 1);
			{
				nimln_(1987, "system.nim");
				while (1) {
					NI TM_YJO1YzEYGZ9aXsNuQl5zaUw_33;
					if (!(res <= ((NI) 512))) goto LA13;
					nimln_(1988, "system.nim");
					y = ((NI)chckRange(res, ((NI) 1), ((NI) 512)));
					{
						NI x;
						NI volatile res_2;
						x = (NI)0;
						nimln_(1986, "system.nim");
						res_2 = ((NI) 1);
						{
							nimln_(1987, "system.nim");
							while (1) {
								tyArray_nHXaesL0DJZHyVS07ARPRA T17_;
								NimStringDesc* T18_;
								NI T19_;
								NimStringDesc* T20_;
								NI T21_;
								NimStringDesc* T22_;
								NI T23_;
								NimStringDesc* T24_;
								NI TM_YJO1YzEYGZ9aXsNuQl5zaUw_32;
								if (!(res_2 <= ((NI) 512))) goto LA16;
								nimln_(1988, "system.nim");
								x = ((NI)chckRange(res_2, ((NI) 1), ((NI) 512)));
								nimln_(28, "filewrite.nim");
								memset((void*)T17_, 0, sizeof(T17_));
								T18_ = (NimStringDesc*)0;
								if (x < 1 || x > 512) raiseIndexError();
								if (y < 1 || y > 512) raiseIndexError();
								T19_ = (NI)0;
								T19_ = toInt_glNdNQuZoVn2fP9bTsL9ckOw(img[(x)- 1][(y)- 1][(((NI) 0))- 0]);
								T20_ = (NimStringDesc*)0;
								T20_ = nimIntToStr(T19_);
								if (x < 1 || x > 512) raiseIndexError();
								if (y < 1 || y > 512) raiseIndexError();
								T21_ = (NI)0;
								T21_ = toInt_glNdNQuZoVn2fP9bTsL9ckOw(-(img[(x)- 1][(y)- 1][(((NI) 1))- 0]));
								T22_ = (NimStringDesc*)0;
								T22_ = nimIntToStr(T21_);
								if (x < 1 || x > 512) raiseIndexError();
								if (y < 1 || y > 512) raiseIndexError();
								T23_ = (NI)0;
								T23_ = toInt_glNdNQuZoVn2fP9bTsL9ckOw(img[(x)- 1][(y)- 1][(((NI) 2))- 0]);
								T24_ = (NimStringDesc*)0;
								T24_ = nimIntToStr(T23_);
								T18_ = rawNewString(T20_->Sup.len + T22_->Sup.len + T24_->Sup.len + 2);
appendString(T18_, T20_);
appendString(T18_, ((NimStringDesc*) &TM_YJO1YzEYGZ9aXsNuQl5zaUw_29));
appendString(T18_, T22_);
appendString(T18_, ((NimStringDesc*) &TM_YJO1YzEYGZ9aXsNuQl5zaUw_29));
appendString(T18_, T24_);
								T17_[0] = T18_;
								writeLine_rBQVO3cm3BhnA9aEFD7PG6Qclassical(f, T17_, 1);
								nimln_(1989, "system.nim");
								TM_YJO1YzEYGZ9aXsNuQl5zaUw_32 = addInt(res_2, ((NI) 1));
								res_2 = (NI)(TM_YJO1YzEYGZ9aXsNuQl5zaUw_32);
							} LA16: ;
						}
					}
					TM_YJO1YzEYGZ9aXsNuQl5zaUw_33 = addInt(res, ((NI) 1));
					res = (NI)(TM_YJO1YzEYGZ9aXsNuQl5zaUw_33);
				} LA13: ;
			}
		}
		popSafePoint();
	}
	else {
		popSafePoint();
		setFrame((TFrame*)&FR_);
	}
	{
		nimln_(20, "filewrite.nim");
		close_BWnr8V7RERYno9bIdPmw8Hw_2(f);
		nimln_(21, "filewrite.nim");
		printf("%s\012", ((NimStringDesc*) &TM_YJO1YzEYGZ9aXsNuQl5zaUw_34)? (((NimStringDesc*) &TM_YJO1YzEYGZ9aXsNuQl5zaUw_34))->data:"nil");
		fflush(stdout);
	}
	if (TM_YJO1YzEYGZ9aXsNuQl5zaUw_22.status != 0) reraiseException();
	popFrame();
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner(void) {
	systemInit000();
	stdlib_parseutilsDatInit000();
	stdlib_mathDatInit000();
	stdlib_algorithmDatInit000();
	stdlib_strutilsDatInit000();
	stdlib_timesDatInit000();
	classicalDatInit000();
	stdlib_parseutilsInit000();
	stdlib_mathInit000();
	stdlib_algorithmInit000();
	stdlib_strutilsInit000();
	stdlib_timesInit000();
}

void PreMain(void) {
	void (*volatile inner)(void);
	systemDatInit000();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void) {
	tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ T1_;
	tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ T2_;
	NimStringDesc* T30_;
	time_t T31_;
	tyObject_TimeInfo_sGezGiKtnmyCJvsDB0xApg T32_;
	NimStringDesc* T33_;
	nimfr_("classical", "classical.nim");
nimRegisterGlobalMarker(TM_YJO1YzEYGZ9aXsNuQl5zaUw_8);
nimRegisterGlobalMarker(TM_YJO1YzEYGZ9aXsNuQl5zaUw_13);
nimRegisterGlobalMarker(TM_YJO1YzEYGZ9aXsNuQl5zaUw_14);
nimRegisterGlobalMarker(TM_YJO1YzEYGZ9aXsNuQl5zaUw_15);
nimRegisterGlobalMarker(TM_YJO1YzEYGZ9aXsNuQl5zaUw_16);
	nimln_(9, "classical.nim");
	if (spheres_kh1Yb53gCvZuGB9cEty7Ixw) { nimGCunrefRC1(spheres_kh1Yb53gCvZuGB9cEty7Ixw); spheres_kh1Yb53gCvZuGB9cEty7Ixw = NIM_NIL; }
	spheres_kh1Yb53gCvZuGB9cEty7Ixw = (tySequence_PcQFOjbvH9cE4G4VxStTXaQ*) newSeqRC1((&NTI_PcQFOjbvH9cE4G4VxStTXaQ_), 2);
	nimln_(10, "classical.nim");
	memset((void*)T1_, 0, sizeof(T1_));
	vinit_D0k7o2Q7t4kMjeKeSQkHsA(0.0, 0.0, 1.0000000000000000e+00, T1_);
	asgnRef((void**) (&spheres_kh1Yb53gCvZuGB9cEty7Ixw->data[0]), sinit_kI4YLVrvCnubYMh35jX64A(2.9999999999999999e-01, T1_));
	nimln_(14, "classical.nim");
	memset((void*)T2_, 0, sizeof(T2_));
	vinit_D0k7o2Q7t4kMjeKeSQkHsA(0.0, 0.0, 1.0000200000000000e+05, T2_);
	asgnRef((void**) (&spheres_kh1Yb53gCvZuGB9cEty7Ixw->data[1]), sinit_kI4YLVrvCnubYMh35jX64A(1.0000000000000000e+05, T2_));
	{
		NI res;
		nimln_(1986, "system.nim");
		res = ((NI) 1);
		{
			nimln_(1987, "system.nim");
			while (1) {
				NI TM_YJO1YzEYGZ9aXsNuQl5zaUw_20;
				if (!(res <= ((NI) 512))) goto LA5;
				nimln_(1988, "system.nim");
				x_Bm3EbA5a9a9ae3uTNftAm1aw = ((NI)chckRange(res, ((NI) 1), ((NI) 512)));
				{
					NI res_2;
					y_3BnVL7bQV7oWgWI8lHQ9cnA = 0;
					nimln_(1986, "system.nim");
					res_2 = ((NI) 1);
					{
						nimln_(1987, "system.nim");
						while (1) {
							NI TM_YJO1YzEYGZ9aXsNuQl5zaUw_9;
							NI TM_YJO1YzEYGZ9aXsNuQl5zaUw_10;
							NF T9_;
							NI TM_YJO1YzEYGZ9aXsNuQl5zaUw_11;
							NI TM_YJO1YzEYGZ9aXsNuQl5zaUw_12;
							NF T10_;
							tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ T11_;
							tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ T12_;
							tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ T13_;
							tyObject_IntersectioncolonObjectType__9a3vySMeWlHTn9cS4C42OloA* T14_;
							NI TM_YJO1YzEYGZ9aXsNuQl5zaUw_19;
							if (!(res_2 <= ((NI) 512))) goto LA8;
							nimln_(1988, "system.nim");
							y_3BnVL7bQV7oWgWI8lHQ9cnA = ((NI)chckRange(res_2, ((NI) 1), ((NI) 512)));
							chckNil((void*)o_1PRQa9bVBwRgYsdCVXZEHdw);
							genericReset((void*)o_1PRQa9bVBwRgYsdCVXZEHdw, (&NTI_9ce69c9a1NzlPVqY9aKHS79b5IQ_));
							nimln_(25, "classical.nim");
							TM_YJO1YzEYGZ9aXsNuQl5zaUw_9 = mulInt(((NI) 2), ((NI) (x_Bm3EbA5a9a9ae3uTNftAm1aw)));
							TM_YJO1YzEYGZ9aXsNuQl5zaUw_10 = subInt(((NI) ((NI)(TM_YJO1YzEYGZ9aXsNuQl5zaUw_9))), ((NI) 512));
							T9_ = (NF)0;
							T9_ = slash__fu0hCFNNw3xnGgcs2KwTWgsystem(((NI) ((NI)(TM_YJO1YzEYGZ9aXsNuQl5zaUw_10))), ((NI) 512));
							TM_YJO1YzEYGZ9aXsNuQl5zaUw_11 = mulInt(((NI) 2), ((NI) (y_3BnVL7bQV7oWgWI8lHQ9cnA)));
							TM_YJO1YzEYGZ9aXsNuQl5zaUw_12 = subInt(((NI) ((NI)(TM_YJO1YzEYGZ9aXsNuQl5zaUw_11))), ((NI) 512));
							T10_ = (NF)0;
							T10_ = slash__fu0hCFNNw3xnGgcs2KwTWgsystem(((NI) ((NI)(TM_YJO1YzEYGZ9aXsNuQl5zaUw_12))), ((NI) 512));
							chckNil((void*)o_1PRQa9bVBwRgYsdCVXZEHdw);
							genericReset((void*)o_1PRQa9bVBwRgYsdCVXZEHdw, (&NTI_9ce69c9a1NzlPVqY9aKHS79b5IQ_));
							vinit_D0k7o2Q7t4kMjeKeSQkHsA(T9_, T10_, -1.0000000000000000e+00, o_1PRQa9bVBwRgYsdCVXZEHdw);
							asgnRef((void**) (&ray_KN4t3FfPCNhMHU1EQvoM9cw), NIM_NIL);
							nimln_(26, "classical.nim");
							nimln_(7, "vector3.nim");
							memset((void*)T11_, 0, sizeof(T11_));
							vinit_D0k7o2Q7t4kMjeKeSQkHsA(0.0, 0.0, 0.0, T11_);
							memset((void*)T12_, 0, sizeof(T12_));
							minus__YF7YCu9cPizpHse0BRX79b2w_2(T11_, o_1PRQa9bVBwRgYsdCVXZEHdw, T12_);
							memset((void*)T13_, 0, sizeof(T13_));
							normalize_MDc79btIcKT7GafFDU9aTVLA(T12_, T13_);
							asgnRef((void**) (&ray_KN4t3FfPCNhMHU1EQvoM9cw), rinit_2tN9c9bGVgB9cwiKTQmw6xNdg(o_1PRQa9bVBwRgYsdCVXZEHdw, T13_));
							asgnRef((void**) (&near_gRNrQG3q6ISClYgsw4cwmQ), NIM_NIL);
							nimln_(28, "classical.nim");
							T14_ = (tyObject_IntersectioncolonObjectType__9a3vySMeWlHTn9cS4C42OloA*)0;
							T14_ = (tyObject_IntersectioncolonObjectType__9a3vySMeWlHTn9cS4C42OloA*) newObj((&NTI_pz9bTTOY0l9ckLJHmqRuTH0w_), sizeof(tyObject_IntersectioncolonObjectType__9a3vySMeWlHTn9cS4C42OloA));
							(*T14_).Sup.m_type = (&NTI_9a3vySMeWlHTn9cS4C42OloA_);
							(*T14_).distance = 1.0000000000000000e+15;
							asgnRef((void**) (&near_gRNrQG3q6ISClYgsw4cwmQ), T14_);
							{
								NI i;
								NI L;
								NI T16_;
								asgnRef((void**) (&sphere_TwHbp9bLlawSqh9bEjXlztmg), NIM_NIL);
								nimln_(3639, "system.nim");
								i = ((NI) 0);
								nimln_(3640, "system.nim");
								T16_ = (spheres_kh1Yb53gCvZuGB9cEty7Ixw ? spheres_kh1Yb53gCvZuGB9cEty7Ixw->Sup.len : 0);
								L = T16_;
								{
									nimln_(3641, "system.nim");
									while (1) {
										NI TM_YJO1YzEYGZ9aXsNuQl5zaUw_17;
										if (!(i < L)) goto LA18;
										nimln_(3642, "system.nim");
										if ((NU)(i) >= (NU)(spheres_kh1Yb53gCvZuGB9cEty7Ixw->Sup.len)) raiseIndexError();
										asgnRef((void**) (&sphere_TwHbp9bLlawSqh9bEjXlztmg), spheres_kh1Yb53gCvZuGB9cEty7Ixw->data[i]);
										asgnRef((void**) (&intersection_l44uuhk7TH2yIMpMMOPJWg), NIM_NIL);
										nimln_(30, "classical.nim");
										asgnRef((void**) (&intersection_l44uuhk7TH2yIMpMMOPJWg), intersect_8mMOFsZ3yHkWEpNJZVBcdQ(ray_KN4t3FfPCNhMHU1EQvoM9cw, sphere_TwHbp9bLlawSqh9bEjXlztmg));
										nimln_(31, "classical.nim");
										{
											NIM_BOOL T21_;
											T21_ = (NIM_BOOL)0;
											nimln_(378, "system.nim");
											nimln_(31, "classical.nim");
											T21_ = !((intersection_l44uuhk7TH2yIMpMMOPJWg == NIM_NIL));
											if (!(T21_)) goto LA22_;
											T21_ = ((*intersection_l44uuhk7TH2yIMpMMOPJWg).distance < (*near_gRNrQG3q6ISClYgsw4cwmQ).distance);
											LA22_: ;
											if (!T21_) goto LA23_;
											nimln_(32, "classical.nim");
											asgnRef((void**) (&near_gRNrQG3q6ISClYgsw4cwmQ), intersection_l44uuhk7TH2yIMpMMOPJWg);
										}
										LA23_: ;
										nimln_(3643, "system.nim");
										TM_YJO1YzEYGZ9aXsNuQl5zaUw_17 = addInt(i, ((NI) 1));
										i = (NI)(TM_YJO1YzEYGZ9aXsNuQl5zaUw_17);
										nimln_(3644, "system.nim");
										{
											NI T27_;
											T27_ = (spheres_kh1Yb53gCvZuGB9cEty7Ixw ? spheres_kh1Yb53gCvZuGB9cEty7Ixw->Sup.len : 0);
											if (!!((T27_ == L))) goto LA28_;
											failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_YJO1YzEYGZ9aXsNuQl5zaUw_18));
										}
										LA28_: ;
									} LA18: ;
								}
							}
							if (x_Bm3EbA5a9a9ae3uTNftAm1aw < 1 || x_Bm3EbA5a9a9ae3uTNftAm1aw > 512) raiseIndexError();
							if (y_3BnVL7bQV7oWgWI8lHQ9cnA < 1 || y_3BnVL7bQV7oWgWI8lHQ9cnA > 512) raiseIndexError();
							nimln_(33, "classical.nim");
							memcpy((void*)img_kzpomObqN8W7DgE3OGgP9cw[(x_Bm3EbA5a9a9ae3uTNftAm1aw)- 1][(y_3BnVL7bQV7oWgWI8lHQ9cnA)- 1], (NIM_CONST void*)(*near_gRNrQG3q6ISClYgsw4cwmQ).position, sizeof(tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ));
							nimln_(1989, "system.nim");
							TM_YJO1YzEYGZ9aXsNuQl5zaUw_19 = addInt(res_2, ((NI) 1));
							res_2 = (NI)(TM_YJO1YzEYGZ9aXsNuQl5zaUw_19);
						} LA8: ;
					}
				}
				TM_YJO1YzEYGZ9aXsNuQl5zaUw_20 = addInt(res, ((NI) 1));
				res = (NI)(TM_YJO1YzEYGZ9aXsNuQl5zaUw_20);
			} LA5: ;
		}
	}
	nimln_(36, "classical.nim");
	T30_ = (NimStringDesc*)0;
	T31_ = (time_t)0;
	T31_ = getTime_Ft5FFURWITtb9aR6Hjpq6UQ();
	memset((void*)(&T32_), 0, sizeof(T32_));
	T32_.Sup.m_type = (&NTI_sGezGiKtnmyCJvsDB0xApg_);
	getLocalTime_Ql5lAb5s0QPmy9b8QhS3ucg_2(T31_, (&T32_));
	T33_ = (NimStringDesc*)0;
	T33_ = format_yA59a7f0M79aw68UsupvAfRA((&T32_), ((NimStringDesc*) &TM_YJO1YzEYGZ9aXsNuQl5zaUw_36));
	T30_ = rawNewString(T33_->Sup.len + 7);
appendString(T30_, ((NimStringDesc*) &TM_YJO1YzEYGZ9aXsNuQl5zaUw_35));
appendString(T30_, T33_);
appendString(T30_, ((NimStringDesc*) &TM_YJO1YzEYGZ9aXsNuQl5zaUw_37));
	ppmFileWrite_n3DR45ExtAtzSFu9amJ8c5g(T30_, img_kzpomObqN8W7DgE3OGgP9cw);
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, classicalDatInit000)(void) {
static TNimNode* TM_YJO1YzEYGZ9aXsNuQl5zaUw_5[2];
static TNimNode* TM_YJO1YzEYGZ9aXsNuQl5zaUw_6[2];
static TNimNode* TM_YJO1YzEYGZ9aXsNuQl5zaUw_7[3];
static TNimNode TM_YJO1YzEYGZ9aXsNuQl5zaUw_0[10];
NTI_LG8JyU20iwDlynW9by9bNTjg_.size = sizeof(tyObject_RaycolonObjectType__LG8JyU20iwDlynW9by9bNTjg);
NTI_LG8JyU20iwDlynW9by9bNTjg_.kind = 17;
NTI_LG8JyU20iwDlynW9by9bNTjg_.base = (&NTI_13RNkKqUOX1TtorOUlKtqA_);
NTI_LG8JyU20iwDlynW9by9bNTjg_.flags = 1;
TM_YJO1YzEYGZ9aXsNuQl5zaUw_5[0] = &TM_YJO1YzEYGZ9aXsNuQl5zaUw_0[1];
NTI_9ce69c9a1NzlPVqY9aKHS79b5IQ_.size = sizeof(tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ);
NTI_9ce69c9a1NzlPVqY9aKHS79b5IQ_.kind = 16;
NTI_9ce69c9a1NzlPVqY9aKHS79b5IQ_.base = (&NTI_w9bl9a1ul9ctRJWiMl9cNnIMvg_);
NTI_9ce69c9a1NzlPVqY9aKHS79b5IQ_.flags = 3;
TM_YJO1YzEYGZ9aXsNuQl5zaUw_0[1].kind = 1;
TM_YJO1YzEYGZ9aXsNuQl5zaUw_0[1].offset = offsetof(tyObject_RaycolonObjectType__LG8JyU20iwDlynW9by9bNTjg, origin);
TM_YJO1YzEYGZ9aXsNuQl5zaUw_0[1].typ = (&NTI_9ce69c9a1NzlPVqY9aKHS79b5IQ_);
TM_YJO1YzEYGZ9aXsNuQl5zaUw_0[1].name = "origin";
TM_YJO1YzEYGZ9aXsNuQl5zaUw_5[1] = &TM_YJO1YzEYGZ9aXsNuQl5zaUw_0[2];
TM_YJO1YzEYGZ9aXsNuQl5zaUw_0[2].kind = 1;
TM_YJO1YzEYGZ9aXsNuQl5zaUw_0[2].offset = offsetof(tyObject_RaycolonObjectType__LG8JyU20iwDlynW9by9bNTjg, direction);
TM_YJO1YzEYGZ9aXsNuQl5zaUw_0[2].typ = (&NTI_9ce69c9a1NzlPVqY9aKHS79b5IQ_);
TM_YJO1YzEYGZ9aXsNuQl5zaUw_0[2].name = "direction";
TM_YJO1YzEYGZ9aXsNuQl5zaUw_0[0].len = 2; TM_YJO1YzEYGZ9aXsNuQl5zaUw_0[0].kind = 2; TM_YJO1YzEYGZ9aXsNuQl5zaUw_0[0].sons = &TM_YJO1YzEYGZ9aXsNuQl5zaUw_5[0];
NTI_LG8JyU20iwDlynW9by9bNTjg_.node = &TM_YJO1YzEYGZ9aXsNuQl5zaUw_0[0];
NTI_DiBA8cLtLR9bH7Y3ONjjOfg_.size = sizeof(tyObject_RaycolonObjectType__LG8JyU20iwDlynW9by9bNTjg*);
NTI_DiBA8cLtLR9bH7Y3ONjjOfg_.kind = 22;
NTI_DiBA8cLtLR9bH7Y3ONjjOfg_.base = (&NTI_LG8JyU20iwDlynW9by9bNTjg_);
NTI_DiBA8cLtLR9bH7Y3ONjjOfg_.marker = Marker_tyRef_DiBA8cLtLR9bH7Y3ONjjOfg;
NTI_xgLbzOdh3TOGcRIt0sPK9bw_.size = sizeof(tyObject_SpherecolonObjectType__xgLbzOdh3TOGcRIt0sPK9bw);
NTI_xgLbzOdh3TOGcRIt0sPK9bw_.kind = 17;
NTI_xgLbzOdh3TOGcRIt0sPK9bw_.base = (&NTI_13RNkKqUOX1TtorOUlKtqA_);
NTI_xgLbzOdh3TOGcRIt0sPK9bw_.flags = 1;
TM_YJO1YzEYGZ9aXsNuQl5zaUw_6[0] = &TM_YJO1YzEYGZ9aXsNuQl5zaUw_0[4];
TM_YJO1YzEYGZ9aXsNuQl5zaUw_0[4].kind = 1;
TM_YJO1YzEYGZ9aXsNuQl5zaUw_0[4].offset = offsetof(tyObject_SpherecolonObjectType__xgLbzOdh3TOGcRIt0sPK9bw, radius);
TM_YJO1YzEYGZ9aXsNuQl5zaUw_0[4].typ = (&NTI_w9bl9a1ul9ctRJWiMl9cNnIMvg_);
TM_YJO1YzEYGZ9aXsNuQl5zaUw_0[4].name = "radius";
TM_YJO1YzEYGZ9aXsNuQl5zaUw_6[1] = &TM_YJO1YzEYGZ9aXsNuQl5zaUw_0[5];
TM_YJO1YzEYGZ9aXsNuQl5zaUw_0[5].kind = 1;
TM_YJO1YzEYGZ9aXsNuQl5zaUw_0[5].offset = offsetof(tyObject_SpherecolonObjectType__xgLbzOdh3TOGcRIt0sPK9bw, position);
TM_YJO1YzEYGZ9aXsNuQl5zaUw_0[5].typ = (&NTI_9ce69c9a1NzlPVqY9aKHS79b5IQ_);
TM_YJO1YzEYGZ9aXsNuQl5zaUw_0[5].name = "position";
TM_YJO1YzEYGZ9aXsNuQl5zaUw_0[3].len = 2; TM_YJO1YzEYGZ9aXsNuQl5zaUw_0[3].kind = 2; TM_YJO1YzEYGZ9aXsNuQl5zaUw_0[3].sons = &TM_YJO1YzEYGZ9aXsNuQl5zaUw_6[0];
NTI_xgLbzOdh3TOGcRIt0sPK9bw_.node = &TM_YJO1YzEYGZ9aXsNuQl5zaUw_0[3];
NTI_cMwI9aQXCL1qs8LOMk8N9cBg_.size = sizeof(tyObject_SpherecolonObjectType__xgLbzOdh3TOGcRIt0sPK9bw*);
NTI_cMwI9aQXCL1qs8LOMk8N9cBg_.kind = 22;
NTI_cMwI9aQXCL1qs8LOMk8N9cBg_.base = (&NTI_xgLbzOdh3TOGcRIt0sPK9bw_);
NTI_cMwI9aQXCL1qs8LOMk8N9cBg_.marker = Marker_tyRef_cMwI9aQXCL1qs8LOMk8N9cBg;
NTI_9a3vySMeWlHTn9cS4C42OloA_.size = sizeof(tyObject_IntersectioncolonObjectType__9a3vySMeWlHTn9cS4C42OloA);
NTI_9a3vySMeWlHTn9cS4C42OloA_.kind = 17;
NTI_9a3vySMeWlHTn9cS4C42OloA_.base = (&NTI_13RNkKqUOX1TtorOUlKtqA_);
NTI_9a3vySMeWlHTn9cS4C42OloA_.flags = 1;
TM_YJO1YzEYGZ9aXsNuQl5zaUw_7[0] = &TM_YJO1YzEYGZ9aXsNuQl5zaUw_0[7];
TM_YJO1YzEYGZ9aXsNuQl5zaUw_0[7].kind = 1;
TM_YJO1YzEYGZ9aXsNuQl5zaUw_0[7].offset = offsetof(tyObject_IntersectioncolonObjectType__9a3vySMeWlHTn9cS4C42OloA, distance);
TM_YJO1YzEYGZ9aXsNuQl5zaUw_0[7].typ = (&NTI_w9bl9a1ul9ctRJWiMl9cNnIMvg_);
TM_YJO1YzEYGZ9aXsNuQl5zaUw_0[7].name = "distance";
TM_YJO1YzEYGZ9aXsNuQl5zaUw_7[1] = &TM_YJO1YzEYGZ9aXsNuQl5zaUw_0[8];
TM_YJO1YzEYGZ9aXsNuQl5zaUw_0[8].kind = 1;
TM_YJO1YzEYGZ9aXsNuQl5zaUw_0[8].offset = offsetof(tyObject_IntersectioncolonObjectType__9a3vySMeWlHTn9cS4C42OloA, position);
TM_YJO1YzEYGZ9aXsNuQl5zaUw_0[8].typ = (&NTI_9ce69c9a1NzlPVqY9aKHS79b5IQ_);
TM_YJO1YzEYGZ9aXsNuQl5zaUw_0[8].name = "position";
TM_YJO1YzEYGZ9aXsNuQl5zaUw_7[2] = &TM_YJO1YzEYGZ9aXsNuQl5zaUw_0[9];
TM_YJO1YzEYGZ9aXsNuQl5zaUw_0[9].kind = 1;
TM_YJO1YzEYGZ9aXsNuQl5zaUw_0[9].offset = offsetof(tyObject_IntersectioncolonObjectType__9a3vySMeWlHTn9cS4C42OloA, normal);
TM_YJO1YzEYGZ9aXsNuQl5zaUw_0[9].typ = (&NTI_9ce69c9a1NzlPVqY9aKHS79b5IQ_);
TM_YJO1YzEYGZ9aXsNuQl5zaUw_0[9].name = "normal";
TM_YJO1YzEYGZ9aXsNuQl5zaUw_0[6].len = 3; TM_YJO1YzEYGZ9aXsNuQl5zaUw_0[6].kind = 2; TM_YJO1YzEYGZ9aXsNuQl5zaUw_0[6].sons = &TM_YJO1YzEYGZ9aXsNuQl5zaUw_7[0];
NTI_9a3vySMeWlHTn9cS4C42OloA_.node = &TM_YJO1YzEYGZ9aXsNuQl5zaUw_0[6];
NTI_pz9bTTOY0l9ckLJHmqRuTH0w_.size = sizeof(tyObject_IntersectioncolonObjectType__9a3vySMeWlHTn9cS4C42OloA*);
NTI_pz9bTTOY0l9ckLJHmqRuTH0w_.kind = 22;
NTI_pz9bTTOY0l9ckLJHmqRuTH0w_.base = (&NTI_9a3vySMeWlHTn9cS4C42OloA_);
NTI_pz9bTTOY0l9ckLJHmqRuTH0w_.marker = Marker_tyRef_pz9bTTOY0l9ckLJHmqRuTH0w;
NTI_PcQFOjbvH9cE4G4VxStTXaQ_.size = sizeof(tySequence_PcQFOjbvH9cE4G4VxStTXaQ*);
NTI_PcQFOjbvH9cE4G4VxStTXaQ_.kind = 24;
NTI_PcQFOjbvH9cE4G4VxStTXaQ_.base = (&NTI_cMwI9aQXCL1qs8LOMk8N9cBg_);
NTI_PcQFOjbvH9cE4G4VxStTXaQ_.marker = Marker_tySequence_PcQFOjbvH9cE4G4VxStTXaQ;
}

