/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w  -I/usr/local/Cellar/nim/0.18.0_1/nim/lib -o /Users/nao/Documents/ray/nim-ray/nimcache/edupt.o /Users/nao/Documents/ray/nim-ray/nimcache/edupt.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <stdio.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyObject_CameracolonObjectType__wUoYkr9ctvY5yqacRBRq5ww tyObject_CameracolonObjectType__wUoYkr9ctvY5yqacRBRq5ww;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct RootObj RootObj;
typedef struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack_7fytPA5bBsob6See21YMRA tyObject_GcStack_7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyTuple_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct tyObject_SpherecolonObjectType__EnbbGzdxyUrulo0Zp8QWAg tyObject_SpherecolonObjectType__EnbbGzdxyUrulo0Zp8QWAg;
typedef struct tyObject_RaycolonObjectType__yItp9be63YkzBMUq0NA9cyMQ tyObject_RaycolonObjectType__yItp9be63YkzBMUq0NA9cyMQ;
typedef struct tyObject_IntersectioncolonObjectType__ez5BZXnG89cynYRdZ8nGXQA tyObject_IntersectioncolonObjectType__ez5BZXnG89cynYRdZ8nGXQA;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyObject_DateTime_S7qec11z7km5Pal3UXrHmw tyObject_DateTime_S7qec11z7km5Pal3UXrHmw;
typedef struct tyObject_Timezone_g1TRr0fUzr8gtJpVPUSSnA tyObject_Timezone_g1TRr0fUzr8gtJpVPUSSnA;
typedef struct tyObject_ZonedTime_WigfH9apQAxJ69bBPh3wB8RQ tyObject_ZonedTime_WigfH9apQAxJ69bBPh3wB8RQ;
typedef struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ;
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct RootObj {
TNimType* m_type;
};
typedef NF tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ[3];
struct tyObject_CameracolonObjectType__wUoYkr9ctvY5yqacRBRq5ww {
  RootObj Sup;
tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ position;
tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ direction;
};
typedef N_NIMCALL_PTR(void, tyProc_T4eqaYlFJYZUv9aG9b1TV0bQ) (void);
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* tyArray_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef NU32 tyArray_BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* tyArray_N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray_N1u1nqOgmuJN9cSZrnMHgOQ tyArray_B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* tyArray_lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA {
tyArray_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* tyArray_0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
tyArray_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyArray_LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray_LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
NU32 flBitmap;
tyArray_BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray_B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
NI gcThreadId;
};
typedef tyObject_SpherecolonObjectType__EnbbGzdxyUrulo0Zp8QWAg* tyArray_BfCmlBC6y7NSMojmnRC5Fw[2];
typedef tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ tyArray_GQhcrJiMJzzylpLOa69cyiQ[512];
typedef tyArray_GQhcrJiMJzzylpLOa69cyiQ tyArray_9bH8Ed9bT7Ap1KqYu3IKfp4Q[512];
struct tyObject_IntersectioncolonObjectType__ez5BZXnG89cynYRdZ8nGXQA {
  RootObj Sup;
NF distance;
tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ position;
tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ normal;
tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ color;
};
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NU8 tyEnum_Month_JS0JuFvCBbC2GL3xXBnPQw;
typedef NU8 tyEnum_WeekDay_SVfemTA9aCOyua2TJYa6yBg;
struct tyObject_ZonedTime_WigfH9apQAxJ69bBPh3wB8RQ {
NI64 adjTime;
NI utcOffset;
NIM_BOOL isDst;
};
typedef struct {
N_NIMCALL_PTR(tyObject_ZonedTime_WigfH9apQAxJ69bBPh3wB8RQ, ClP_0) (NI64 time, void* ClE_0);
void* ClE_0;
} tyProc_ye9aJuuf18PyKew55REW9aIA;
struct tyObject_Timezone_g1TRr0fUzr8gtJpVPUSSnA {
tyProc_ye9aJuuf18PyKew55REW9aIA zoneInfoFromUtc;
tyProc_ye9aJuuf18PyKew55REW9aIA zoneInfoFromTz;
NimStringDesc* name;
};
struct tyObject_DateTime_S7qec11z7km5Pal3UXrHmw {
  RootObj Sup;
NI second;
NI minute;
NI hour;
NI monthday;
tyEnum_Month_JS0JuFvCBbC2GL3xXBnPQw month;
NI year;
tyEnum_WeekDay_SVfemTA9aCOyua2TJYa6yBg weekday;
NI yearday;
NIM_BOOL isDst;
tyObject_Timezone_g1TRr0fUzr8gtJpVPUSSnA timezone;
NI utcOffset;
};
struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w {
NI prevSize;
NI size;
};
struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* next;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* freeList;
NI free;
NI acc;
NF data;
};
struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* next;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NF data;
};
struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw {
NI size;
NI acc;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* next;
};
typedef NI tyArray_9a8QARi5WsUggNU9bom7kzTQ[8];
struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw {
tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg {
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_SpherecolonObjectType__EnbbGzdxyUrulo0Zp8QWAg {
  RootObj Sup;
NF radius;
tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ position;
tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ emission;
tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ color;
};
struct tyObject_RaycolonObjectType__yItp9be63YkzBMUq0NA9cyMQ {
  RootObj Sup;
tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ origin;
tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ direction;
};
struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ {
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zeroField;
};
static N_NIMCALL(void, Marker_tyRef_Jq0umG5Kvy9bYKAgRHqrCBQ)(void* p, NI op);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, TM_0rfqsLiIrz2bWcIQ3t5rYw_3)(void);
N_NIMCALL(void, nimRegisterGlobalMarker)(tyProc_T4eqaYlFJYZUv9aG9b1TV0bQ markerProc);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_LIB_PRIVATE N_NIMCALL(void, vinit_NR9bsEPN4kVj7xVgDhfHxYg)(NF x, NF y, NF z, tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ Result);
N_LIB_PRIVATE N_NIMCALL(void, normalize_Z0pi1hweFjr4uVVUJE2Rvg)(tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ this_0, tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ Result);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_NIMCALL(void, TM_0rfqsLiIrz2bWcIQ3t5rYw_4)(void);
N_LIB_PRIVATE N_NIMCALL(tyObject_SpherecolonObjectType__EnbbGzdxyUrulo0Zp8QWAg*, sinit_AbZPzgQR9bquGxUjJeTAIGw)(NF radius, tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ position, tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ emission, tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ color);
N_NOINLINE(void, chckNil)(void* p);
N_NIMCALL(void, genericReset)(void* dest, TNimType* mt);
static N_INLINE(NF, slash__fu0hCFNNw3xnGgcs2KwTWgsystem)(NI x, NI y);
N_NIMCALL(NI, mulInt)(NI a, NI b);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_NIMCALL(void, TM_0rfqsLiIrz2bWcIQ3t5rYw_9)(void);
N_LIB_PRIVATE N_NIMCALL(tyObject_RaycolonObjectType__yItp9be63YkzBMUq0NA9cyMQ*, rinit_gHUempGhSyUh2hQWXNTPmw)(tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ o, tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ d);
N_LIB_PRIVATE N_NIMCALL(void, minus__lUId4ok88EeE1RPmV09buIQ_2)(tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ left, tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ right, tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ Result);
static N_NIMCALL(void, TM_0rfqsLiIrz2bWcIQ3t5rYw_10)(void);
static N_NIMCALL(void, TM_0rfqsLiIrz2bWcIQ3t5rYw_11)(void);
N_LIB_PRIVATE N_NIMCALL(tyObject_IntersectioncolonObjectType__ez5BZXnG89cynYRdZ8nGXQA*, intersect_gZG6Bl0EcnZjGa56OIToOw)(tyObject_RaycolonObjectType__yItp9be63YkzBMUq0NA9cyMQ* r, tyObject_SpherecolonObjectType__EnbbGzdxyUrulo0Zp8QWAg* sphere);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(NI, addInt)(NI a, NI b);
N_LIB_PRIVATE N_NIMCALL(void, ppmFileWrite_U4eWJEq9cgGb7B1ka9avleMw)(NimStringDesc* fileName, tyArray_9bH8Ed9bT7Ap1KqYu3IKfp4Q img);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, format_3T6OLpwC4t6tQHwM5gTL4w)(tyObject_DateTime_S7qec11z7km5Pal3UXrHmw* dt, NimStringDesc* f);
N_LIB_PRIVATE N_NIMCALL(void, local_hVIxY9b0jArUwtFpeFlykaw_2)(NI64 t, tyObject_DateTime_S7qec11z7km5Pal3UXrHmw* Result);
N_LIB_PRIVATE N_NIMCALL(NI64, getTime_Ft5FFURWITtb9aR6Hjpq6UQ)(void);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
static N_INLINE(void, writeLine_rBQVO3cm3BhnA9aEFD7PG6Qfilewrite)(FILE* f, NimStringDesc** x, NI xLen_0);
N_LIB_PRIVATE N_NIMCALL(void, write_c4mGyJBvK73pdM22jiweKQ)(FILE* f, NimStringDesc* s);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* theStackBottom);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_posixInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_posixDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, unknown_intersectionInit000)(void);
NIM_EXTERNC N_NOINLINE(void, unknown_intersectionDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, unknown_filewriteInit000)(void);
NIM_EXTERNC N_NOINLINE(void, unknown_filewriteDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void);
NIM_EXTERNC N_NOINLINE(void, eduptDatInit000)(void);
tyObject_CameracolonObjectType__wUoYkr9ctvY5yqacRBRq5ww* camera_RYwTj5tKEj3rDp7SK9cIQyQ;
extern TNimType NTI_13RNkKqUOX1TtorOUlKtqA_;
TNimType NTI_wUoYkr9ctvY5yqacRBRq5ww_;
extern TNimType NTI_9ce69c9a1NzlPVqY9aKHS79b5IQ_;
TNimType NTI_Jq0umG5Kvy9bYKAgRHqrCBQ_;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
tyArray_BfCmlBC6y7NSMojmnRC5Fw spheres_FuvRsJQqBbRlvuocp9cvQbg;
extern TNimType NTI_vmukBQJn5NKYYPIyqS1p2w_;
TNimType NTI_BfCmlBC6y7NSMojmnRC5Fw_;
tyArray_9bH8Ed9bT7Ap1KqYu3IKfp4Q img_C7l9cZgFmHAEME04EQEOx2w;
NI x_YUQzNrror7PHunyErWQQ0Q;
NI y_myaQ9cSGLe9aNL7zt8JaivjA;
tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ o_nxmHMsrA9awD73Ne9b1UTY3w;
tyObject_RaycolonObjectType__yItp9be63YkzBMUq0NA9cyMQ* ray_NlpUaU9cvsbB3d68L2XadBA;
extern TNimType NTI_YJznnTIo305R9akdHV5yqpw_;
tyObject_IntersectioncolonObjectType__ez5BZXnG89cynYRdZ8nGXQA* near_UiO2fve7s9a74th3TBb1lHg;
extern TNimType NTI_ExjOMgSUV9agAX9a7wybnKzw_;
extern TNimType NTI_ez5BZXnG89cynYRdZ8nGXQA_;
NI i_L1tbfQwe6yrOkkiEniovAw;
tyObject_IntersectioncolonObjectType__ez5BZXnG89cynYRdZ8nGXQA* intersection_mPi7ELC4gWRiccEICQUqyg;
extern TNimType NTI_S7qec11z7km5Pal3UXrHmw_;
STRING_LITERAL(TM_0rfqsLiIrz2bWcIQ3t5rYw_15, "img", 3);
STRING_LITERAL(TM_0rfqsLiIrz2bWcIQ3t5rYw_16, "yyyyMMdd-HHmmss", 15);
STRING_LITERAL(TM_0rfqsLiIrz2bWcIQ3t5rYw_17, ".ppm", 4);
STRING_LITERAL(TM_0rfqsLiIrz2bWcIQ3t5rYw_18, "\012", 1);
static N_NIMCALL(void, Marker_tyRef_Jq0umG5Kvy9bYKAgRHqrCBQ)(void* p, NI op) {
	tyObject_CameracolonObjectType__wUoYkr9ctvY5yqacRBRq5ww* a;
	NI T1_;
	NI T2_;
	a = (tyObject_CameracolonObjectType__wUoYkr9ctvY5yqacRBRq5ww*)p;
	T1_ = (NI)0;
	T2_ = (NI)0;
}
static N_NIMCALL(void, TM_0rfqsLiIrz2bWcIQ3t5rYw_3)(void) {
	nimGCvisit((void*)camera_RYwTj5tKEj3rDp7SK9cIQyQ, 0);
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("incRef", "gc.nim");
	nimln_(191, "gc.nim");
	(*c).refcount = (NI)((NU64)((*c).refcount) + (NU64)(((NI) 8)));
	popFrame();
}

static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	nimfr_("usrToCell", "gc.nim");
	result = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln_(132, "gc.nim");
	result = ((tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (ptrdiff_t) (usr))) - (NU64)(((NI)sizeof(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("rtlAddZCT", "gc.nim");
	nimln_(211, "gc.nim");
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
	popFrame();
}

static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("decRef", "gc.nim");
	nimln_(218, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(219, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	nimfr_("asgnRef", "gc.nim");
	nimln_(264, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T5_;
		nimln_(398, "system.nim");
		nimln_(264, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3_;
		T5_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T5_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		incRef_9cAA5YuQAAC3MVbnGeV86swsystem(T5_);
	}
	LA3_: ;
	nimln_(265, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T10_;
		nimln_(398, "system.nim");
		nimln_(265, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA8_;
		T10_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T10_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		decRef_MV4BBk6J1qu70IbBxwEn4wsystem(T10_);
	}
	LA8_: ;
	nimln_(266, "gc.nim");
	(*dest) = src;
	popFrame();
}
static N_NIMCALL(void, TM_0rfqsLiIrz2bWcIQ3t5rYw_4)(void) {
	NI T1_;
	T1_ = (NI)0;
	for (T1_ = 0; T1_ < 2; T1_++) {
	nimGCvisit((void*)spheres_FuvRsJQqBbRlvuocp9cvQbg[T1_], 0);
	}
}

static N_INLINE(NF, slash__fu0hCFNNw3xnGgcs2KwTWgsystem)(NI x, NI y) {
	NF result;
	nimfr_("/", "system.nim");
	result = (NF)0;
	nimln_(3498, "system.nim");
	result = ((NF)(((double) (x))) / (NF)(((double) (y))));
	popFrame();
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}
static N_NIMCALL(void, TM_0rfqsLiIrz2bWcIQ3t5rYw_9)(void) {
	nimGCvisit((void*)ray_NlpUaU9cvsbB3d68L2XadBA, 0);
}
static N_NIMCALL(void, TM_0rfqsLiIrz2bWcIQ3t5rYw_10)(void) {
	nimGCvisit((void*)near_UiO2fve7s9a74th3TBb1lHg, 0);
}
static N_NIMCALL(void, TM_0rfqsLiIrz2bWcIQ3t5rYw_11)(void) {
	nimGCvisit((void*)intersection_mPi7ELC4gWRiccEICQUqyg, 0);
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	copyMem_E1xtACub5WcDa3vbrIXbwgsystem(((void*) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
	(*dest).Sup.len += (*src).Sup.len;
}

static N_INLINE(void, writeLine_rBQVO3cm3BhnA9aEFD7PG6Qfilewrite)(FILE* f, NimStringDesc** x, NI xLen_0) {
	nimfr_("writeLine", "sysio.nim");
	{
		NimStringDesc* i;
		NI i_2;
		i = (NimStringDesc*)0;
		nimln_(2185, "system.nim");
		i_2 = ((NI) 0);
		{
			nimln_(2186, "system.nim");
			while (1) {
				if (!(i_2 < xLen_0)) goto LA3;
				nimln_(2187, "system.nim");
				i = x[i_2];
				nimln_(274, "sysio.nim");
				write_c4mGyJBvK73pdM22jiweKQ(f, i);
				nimln_(2188, "system.nim");
				i_2 += ((NI) 1);
			} LA3: ;
		}
	}
	nimln_(275, "sysio.nim");
	write_c4mGyJBvK73pdM22jiweKQ(f, ((NimStringDesc*) &TM_0rfqsLiIrz2bWcIQ3t5rYw_18));
	popFrame();
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner(void) {
	systemInit000();
	stdlib_parseutilsDatInit000();
	stdlib_mathDatInit000();
	stdlib_algorithmDatInit000();
	stdlib_strutilsDatInit000();
	stdlib_posixDatInit000();
	stdlib_timesDatInit000();
	unknown_intersectionDatInit000();
	unknown_filewriteDatInit000();
	eduptDatInit000();
	stdlib_parseutilsInit000();
	stdlib_mathInit000();
	stdlib_algorithmInit000();
	stdlib_strutilsInit000();
	stdlib_posixInit000();
	stdlib_timesInit000();
	unknown_intersectionInit000();
	unknown_filewriteInit000();
}

void PreMain(void) {
	void (*volatile inner)(void);
	systemDatInit000();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void) {
	tyObject_CameracolonObjectType__wUoYkr9ctvY5yqacRBRq5ww* T1_;
	tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ T2_;
	tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ T3_;
	tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ T4_;
	tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ T5_;
	tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ T6_;
	tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ T7_;
	tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ T8_;
	NimStringDesc* T30_;
	NI64 T31_;
	tyObject_DateTime_S7qec11z7km5Pal3UXrHmw T32_;
	NimStringDesc* T33_;
	nimfr_("edupt", "edupt.nim");
nimRegisterGlobalMarker(TM_0rfqsLiIrz2bWcIQ3t5rYw_3);
nimRegisterGlobalMarker(TM_0rfqsLiIrz2bWcIQ3t5rYw_4);
nimRegisterGlobalMarker(TM_0rfqsLiIrz2bWcIQ3t5rYw_9);
nimRegisterGlobalMarker(TM_0rfqsLiIrz2bWcIQ3t5rYw_10);
nimRegisterGlobalMarker(TM_0rfqsLiIrz2bWcIQ3t5rYw_11);
	nimln_(13, "edupt.nim");
	T1_ = (tyObject_CameracolonObjectType__wUoYkr9ctvY5yqacRBRq5ww*)0;
	T1_ = (tyObject_CameracolonObjectType__wUoYkr9ctvY5yqacRBRq5ww*) newObj((&NTI_Jq0umG5Kvy9bYKAgRHqrCBQ_), sizeof(tyObject_CameracolonObjectType__wUoYkr9ctvY5yqacRBRq5ww));
	(*T1_).Sup.m_type = (&NTI_wUoYkr9ctvY5yqacRBRq5ww_);
	vinit_NR9bsEPN4kVj7xVgDhfHxYg(5.0000000000000000e+01, 5.0000000000000000e+01, -2.2000000000000000e+02, (*T1_).position);
	memset((void*)T2_, 0, sizeof(T2_));
	vinit_NR9bsEPN4kVj7xVgDhfHxYg(0.0, -4.0000000000000001e-02, 1.0000000000000000e+00, T2_);
	normalize_Z0pi1hweFjr4uVVUJE2Rvg(T2_, (*T1_).direction);
	asgnRef((void**) (&camera_RYwTj5tKEj3rDp7SK9cIQyQ), T1_);
	nimln_(18, "edupt.nim");
	nimln_(19, "edupt.nim");
	memset((void*)T3_, 0, sizeof(T3_));
	vinit_NR9bsEPN4kVj7xVgDhfHxYg(0.0, 0.0, 1.0000000000000000e+00, T3_);
	nimln_(6, "vector3.nim");
	memset((void*)T4_, 0, sizeof(T4_));
	vinit_NR9bsEPN4kVj7xVgDhfHxYg(0.0, 0.0, 0.0, T4_);
	nimln_(19, "edupt.nim");
	memset((void*)T5_, 0, sizeof(T5_));
	vinit_NR9bsEPN4kVj7xVgDhfHxYg(9.8999999999999999e-01, 9.8999999999999999e-01, 9.8999999999999999e-01, T5_);
	asgnRef((void**) (&spheres_FuvRsJQqBbRlvuocp9cvQbg[0]), sinit_AbZPzgQR9bquGxUjJeTAIGw(2.9999999999999999e-01, T3_, T4_, T5_));
	nimln_(23, "edupt.nim");
	memset((void*)T6_, 0, sizeof(T6_));
	vinit_NR9bsEPN4kVj7xVgDhfHxYg(0.0, 0.0, 1.0000200000000000e+05, T6_);
	nimln_(6, "vector3.nim");
	memset((void*)T7_, 0, sizeof(T7_));
	vinit_NR9bsEPN4kVj7xVgDhfHxYg(0.0, 0.0, 0.0, T7_);
	nimln_(23, "edupt.nim");
	memset((void*)T8_, 0, sizeof(T8_));
	vinit_NR9bsEPN4kVj7xVgDhfHxYg(2.5000000000000000e-01, 2.5000000000000000e-01, 7.5000000000000000e-01, T8_);
	asgnRef((void**) (&spheres_FuvRsJQqBbRlvuocp9cvQbg[1]), sinit_AbZPzgQR9bquGxUjJeTAIGw(1.0000000000000000e+05, T6_, T7_, T8_));
	{
		NI i;
		nimln_(3519, "system.nim");
		i = ((NI) 0);
		{
			nimln_(3520, "system.nim");
			while (1) {
				NI TM_0rfqsLiIrz2bWcIQ3t5rYw_14;
				if (!(i < ((NI) 512))) goto LA11;
				nimln_(3521, "system.nim");
				x_YUQzNrror7PHunyErWQQ0Q = i;
				{
					NI i_2;
					y_myaQ9cSGLe9aNL7zt8JaivjA = 0;
					nimln_(3519, "system.nim");
					i_2 = ((NI) 0);
					{
						nimln_(3520, "system.nim");
						while (1) {
							NI TM_0rfqsLiIrz2bWcIQ3t5rYw_5;
							NI TM_0rfqsLiIrz2bWcIQ3t5rYw_6;
							NF T15_;
							NI TM_0rfqsLiIrz2bWcIQ3t5rYw_7;
							NI TM_0rfqsLiIrz2bWcIQ3t5rYw_8;
							NF T16_;
							tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ T17_;
							tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ T18_;
							tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ T19_;
							tyObject_IntersectioncolonObjectType__ez5BZXnG89cynYRdZ8nGXQA* T20_;
							NI TM_0rfqsLiIrz2bWcIQ3t5rYw_13;
							if (!(i_2 < ((NI) 512))) goto LA14;
							nimln_(3521, "system.nim");
							y_myaQ9cSGLe9aNL7zt8JaivjA = i_2;
							chckNil((void*)o_nxmHMsrA9awD73Ne9b1UTY3w);
							genericReset((void*)o_nxmHMsrA9awD73Ne9b1UTY3w, (&NTI_9ce69c9a1NzlPVqY9aKHS79b5IQ_));
							nimln_(34, "edupt.nim");
							TM_0rfqsLiIrz2bWcIQ3t5rYw_5 = mulInt(((NI) 2), x_YUQzNrror7PHunyErWQQ0Q);
							TM_0rfqsLiIrz2bWcIQ3t5rYw_6 = subInt((NI)(TM_0rfqsLiIrz2bWcIQ3t5rYw_5), ((NI) 512));
							T15_ = (NF)0;
							T15_ = slash__fu0hCFNNw3xnGgcs2KwTWgsystem((NI)(TM_0rfqsLiIrz2bWcIQ3t5rYw_6), ((NI) 512));
							TM_0rfqsLiIrz2bWcIQ3t5rYw_7 = mulInt(((NI) 2), y_myaQ9cSGLe9aNL7zt8JaivjA);
							TM_0rfqsLiIrz2bWcIQ3t5rYw_8 = subInt((NI)(TM_0rfqsLiIrz2bWcIQ3t5rYw_7), ((NI) 512));
							T16_ = (NF)0;
							T16_ = slash__fu0hCFNNw3xnGgcs2KwTWgsystem((NI)(TM_0rfqsLiIrz2bWcIQ3t5rYw_8), ((NI) 512));
							vinit_NR9bsEPN4kVj7xVgDhfHxYg(T15_, T16_, -1.0000000000000000e+00, o_nxmHMsrA9awD73Ne9b1UTY3w);
							asgnRef((void**) (&ray_NlpUaU9cvsbB3d68L2XadBA), NIM_NIL);
							nimln_(35, "edupt.nim");
							nimln_(6, "vector3.nim");
							memset((void*)T17_, 0, sizeof(T17_));
							vinit_NR9bsEPN4kVj7xVgDhfHxYg(0.0, 0.0, 0.0, T17_);
							memset((void*)T18_, 0, sizeof(T18_));
							minus__lUId4ok88EeE1RPmV09buIQ_2(T17_, o_nxmHMsrA9awD73Ne9b1UTY3w, T18_);
							memset((void*)T19_, 0, sizeof(T19_));
							normalize_Z0pi1hweFjr4uVVUJE2Rvg(T18_, T19_);
							asgnRef((void**) (&ray_NlpUaU9cvsbB3d68L2XadBA), rinit_gHUempGhSyUh2hQWXNTPmw(o_nxmHMsrA9awD73Ne9b1UTY3w, T19_));
							asgnRef((void**) (&near_UiO2fve7s9a74th3TBb1lHg), NIM_NIL);
							nimln_(37, "edupt.nim");
							T20_ = (tyObject_IntersectioncolonObjectType__ez5BZXnG89cynYRdZ8nGXQA*)0;
							T20_ = (tyObject_IntersectioncolonObjectType__ez5BZXnG89cynYRdZ8nGXQA*) newObj((&NTI_ExjOMgSUV9agAX9a7wybnKzw_), sizeof(tyObject_IntersectioncolonObjectType__ez5BZXnG89cynYRdZ8nGXQA));
							(*T20_).Sup.m_type = (&NTI_ez5BZXnG89cynYRdZ8nGXQA_);
							(*T20_).distance = 1.0000000000000000e+15;
							asgnRef((void**) (&near_UiO2fve7s9a74th3TBb1lHg), T20_);
							{
								NI i_3;
								i_L1tbfQwe6yrOkkiEniovAw = 0;
								nimln_(3519, "system.nim");
								i_3 = ((NI) 0);
								{
									nimln_(3520, "system.nim");
									while (1) {
										NI TM_0rfqsLiIrz2bWcIQ3t5rYw_12;
										if (!(i_3 < ((NI) 2))) goto LA23;
										nimln_(3521, "system.nim");
										i_L1tbfQwe6yrOkkiEniovAw = i_3;
										asgnRef((void**) (&intersection_mPi7ELC4gWRiccEICQUqyg), NIM_NIL);
										nimln_(39, "edupt.nim");
										if ((NU)(i_L1tbfQwe6yrOkkiEniovAw) > (NU)(1)) raiseIndexError();
										asgnRef((void**) (&intersection_mPi7ELC4gWRiccEICQUqyg), intersect_gZG6Bl0EcnZjGa56OIToOw(ray_NlpUaU9cvsbB3d68L2XadBA, spheres_FuvRsJQqBbRlvuocp9cvQbg[(i_L1tbfQwe6yrOkkiEniovAw)- 0]));
										nimln_(40, "edupt.nim");
										{
											NIM_BOOL T26_;
											T26_ = (NIM_BOOL)0;
											nimln_(398, "system.nim");
											nimln_(40, "edupt.nim");
											T26_ = !((intersection_mPi7ELC4gWRiccEICQUqyg == NIM_NIL));
											if (!(T26_)) goto LA27_;
											T26_ = ((*intersection_mPi7ELC4gWRiccEICQUqyg).distance < (*near_UiO2fve7s9a74th3TBb1lHg).distance);
											LA27_: ;
											if (!T26_) goto LA28_;
											nimln_(41, "edupt.nim");
											asgnRef((void**) (&near_UiO2fve7s9a74th3TBb1lHg), intersection_mPi7ELC4gWRiccEICQUqyg);
										}
										LA28_: ;
										nimln_(3522, "system.nim");
										TM_0rfqsLiIrz2bWcIQ3t5rYw_12 = addInt(i_3, ((NI) 1));
										i_3 = (NI)(TM_0rfqsLiIrz2bWcIQ3t5rYw_12);
									} LA23: ;
								}
							}
							if ((NU)(x_YUQzNrror7PHunyErWQQ0Q) > (NU)(511)) raiseIndexError();
							if ((NU)(y_myaQ9cSGLe9aNL7zt8JaivjA) > (NU)(511)) raiseIndexError();
							nimln_(42, "edupt.nim");
							memcpy((void*)img_C7l9cZgFmHAEME04EQEOx2w[(x_YUQzNrror7PHunyErWQQ0Q)- 0][(y_myaQ9cSGLe9aNL7zt8JaivjA)- 0], (NIM_CONST void*)(*near_UiO2fve7s9a74th3TBb1lHg).color, sizeof(tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ));
							nimln_(3522, "system.nim");
							TM_0rfqsLiIrz2bWcIQ3t5rYw_13 = addInt(i_2, ((NI) 1));
							i_2 = (NI)(TM_0rfqsLiIrz2bWcIQ3t5rYw_13);
						} LA14: ;
					}
				}
				TM_0rfqsLiIrz2bWcIQ3t5rYw_14 = addInt(i, ((NI) 1));
				i = (NI)(TM_0rfqsLiIrz2bWcIQ3t5rYw_14);
			} LA11: ;
		}
	}
	nimln_(45, "edupt.nim");
	T30_ = (NimStringDesc*)0;
	T31_ = (NI64)0;
	T31_ = getTime_Ft5FFURWITtb9aR6Hjpq6UQ();
	memset((void*)(&T32_), 0, sizeof(T32_));
	T32_.Sup.m_type = (&NTI_S7qec11z7km5Pal3UXrHmw_);
	local_hVIxY9b0jArUwtFpeFlykaw_2(T31_, (&T32_));
	T33_ = (NimStringDesc*)0;
	T33_ = format_3T6OLpwC4t6tQHwM5gTL4w((&T32_), ((NimStringDesc*) &TM_0rfqsLiIrz2bWcIQ3t5rYw_16));
	T30_ = rawNewString(T33_->Sup.len + 7);
appendString(T30_, ((NimStringDesc*) &TM_0rfqsLiIrz2bWcIQ3t5rYw_15));
appendString(T30_, T33_);
appendString(T30_, ((NimStringDesc*) &TM_0rfqsLiIrz2bWcIQ3t5rYw_17));
	ppmFileWrite_U4eWJEq9cgGb7B1ka9avleMw(T30_, img_C7l9cZgFmHAEME04EQEOx2w);
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, eduptDatInit000)(void) {
static TNimNode* TM_0rfqsLiIrz2bWcIQ3t5rYw_2[2];
static TNimNode TM_0rfqsLiIrz2bWcIQ3t5rYw_0[3];
NTI_wUoYkr9ctvY5yqacRBRq5ww_.size = sizeof(tyObject_CameracolonObjectType__wUoYkr9ctvY5yqacRBRq5ww);
NTI_wUoYkr9ctvY5yqacRBRq5ww_.kind = 17;
NTI_wUoYkr9ctvY5yqacRBRq5ww_.base = (&NTI_13RNkKqUOX1TtorOUlKtqA_);
NTI_wUoYkr9ctvY5yqacRBRq5ww_.flags = 1;
TM_0rfqsLiIrz2bWcIQ3t5rYw_2[0] = &TM_0rfqsLiIrz2bWcIQ3t5rYw_0[1];
TM_0rfqsLiIrz2bWcIQ3t5rYw_0[1].kind = 1;
TM_0rfqsLiIrz2bWcIQ3t5rYw_0[1].offset = offsetof(tyObject_CameracolonObjectType__wUoYkr9ctvY5yqacRBRq5ww, position);
TM_0rfqsLiIrz2bWcIQ3t5rYw_0[1].typ = (&NTI_9ce69c9a1NzlPVqY9aKHS79b5IQ_);
TM_0rfqsLiIrz2bWcIQ3t5rYw_0[1].name = "position";
TM_0rfqsLiIrz2bWcIQ3t5rYw_2[1] = &TM_0rfqsLiIrz2bWcIQ3t5rYw_0[2];
TM_0rfqsLiIrz2bWcIQ3t5rYw_0[2].kind = 1;
TM_0rfqsLiIrz2bWcIQ3t5rYw_0[2].offset = offsetof(tyObject_CameracolonObjectType__wUoYkr9ctvY5yqacRBRq5ww, direction);
TM_0rfqsLiIrz2bWcIQ3t5rYw_0[2].typ = (&NTI_9ce69c9a1NzlPVqY9aKHS79b5IQ_);
TM_0rfqsLiIrz2bWcIQ3t5rYw_0[2].name = "direction";
TM_0rfqsLiIrz2bWcIQ3t5rYw_0[0].len = 2; TM_0rfqsLiIrz2bWcIQ3t5rYw_0[0].kind = 2; TM_0rfqsLiIrz2bWcIQ3t5rYw_0[0].sons = &TM_0rfqsLiIrz2bWcIQ3t5rYw_2[0];
NTI_wUoYkr9ctvY5yqacRBRq5ww_.node = &TM_0rfqsLiIrz2bWcIQ3t5rYw_0[0];
NTI_Jq0umG5Kvy9bYKAgRHqrCBQ_.size = sizeof(tyObject_CameracolonObjectType__wUoYkr9ctvY5yqacRBRq5ww*);
NTI_Jq0umG5Kvy9bYKAgRHqrCBQ_.kind = 22;
NTI_Jq0umG5Kvy9bYKAgRHqrCBQ_.base = (&NTI_wUoYkr9ctvY5yqacRBRq5ww_);
NTI_Jq0umG5Kvy9bYKAgRHqrCBQ_.marker = Marker_tyRef_Jq0umG5Kvy9bYKAgRHqrCBQ;
NTI_BfCmlBC6y7NSMojmnRC5Fw_.size = sizeof(tyArray_BfCmlBC6y7NSMojmnRC5Fw);
NTI_BfCmlBC6y7NSMojmnRC5Fw_.kind = 16;
NTI_BfCmlBC6y7NSMojmnRC5Fw_.base = (&NTI_vmukBQJn5NKYYPIyqS1p2w_);
}

