/* Generated by Nim Compiler v0.17.2 */
/*   (c) 2017 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w  -I/usr/local/Cellar/nim/0.17.2/nim/lib -o /Users/nao/Documents/ray/nim-ray/nimcache/filewrite.o /Users/nao/Documents/ray/nim-ray/nimcache/filewrite.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <math.h>
#include <string.h>
#include <setjmp.h>
#include <stdio.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct TSafePoint TSafePoint;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NF tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ[3];
typedef tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ tyArray_GQhcrJiMJzzylpLOa69cyiQ[512];
typedef tyArray_GQhcrJiMJzzylpLOa69cyiQ tyArray_9bH8Ed9bT7Ap1KqYu3IKfp4Q[512];
typedef NU8 tyEnum_FileMode_fVUBHvW79bXUw1j55Oo9avSQ;
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
struct RootObj {
TNimType* m_type;
};
struct Exception {
  RootObj Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
Exception* up;
};
typedef struct {
N_NIMCALL_PTR(NIM_BOOL, ClP_0) (Exception* e, void* ClE_0);
void* ClE_0;
} tyProc_KeeAOYBd84Ofsw6Y7LizaQ;
struct TSafePoint {
TSafePoint* prev;
NI status;
jmp_buf context;
NIM_BOOL hasRaiseAction;
tyProc_KeeAOYBd84Ofsw6Y7LizaQ raiseAction;
};
typedef NimStringDesc* tyArray_nHXaesL0DJZHyVS07ARPRA[1];
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
N_NIMCALL(NF, clamp_MP3SGCxfFIDw6O0yuRRW0g)(NF x);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(NI, to255_BuAG9bvAB6AGfXCWB7MgNVg)(NF x);
N_NIMCALL(FILE*, open_hqzpWQbdA2B8l9a6wwNoP4g)(NimStringDesc* filename, tyEnum_FileMode_fVUBHvW79bXUw1j55Oo9avSQ mode, NI bufSize);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
static N_INLINE(void, pushSafePoint)(TSafePoint* s);
static N_INLINE(void, writeLine_rBQVO3cm3BhnA9aEFD7PG6Qfilewrite)(FILE* f, NimStringDesc** x, NI xLen_0);
N_NIMCALL(void, write_c4mGyJBvK73pdM22jiweKQ)(FILE* f, NimStringDesc* s);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(void, popSafePoint)(void);
static N_INLINE(void, setFrame)(TFrame* s);
N_NIMCALL(void, close_BWnr8V7RERYno9bIdPmw8Hw_2)(FILE* f);
N_NIMCALL(void, reraiseException)(void);
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TSafePoint* excHandler_rqLlY5bs9atDw2OXYqJEn5g;
STRING_LITERAL(TM_DOEFk8Ga9aqsEo1I9b5I20kA_2, "img/", 4);
STRING_LITERAL(TM_DOEFk8Ga9aqsEo1I9b5I20kA_4, "\012", 1);
STRING_LITERAL(TM_DOEFk8Ga9aqsEo1I9b5I20kA_6, "P3", 2);
NIM_CONST tyArray_nHXaesL0DJZHyVS07ARPRA TM_DOEFk8Ga9aqsEo1I9b5I20kA_5 = {((NimStringDesc*) &TM_DOEFk8Ga9aqsEo1I9b5I20kA_6)}
;
STRING_LITERAL(TM_DOEFk8Ga9aqsEo1I9b5I20kA_7, "# The P3 means colors are in ASCII, then ", 41);
STRING_LITERAL(TM_DOEFk8Ga9aqsEo1I9b5I20kA_8, " columns and ", 13);
STRING_LITERAL(TM_DOEFk8Ga9aqsEo1I9b5I20kA_9, " rows, then 255 for max color, then RGB triplets", 48);
STRING_LITERAL(TM_DOEFk8Ga9aqsEo1I9b5I20kA_10, " ", 1);
STRING_LITERAL(TM_DOEFk8Ga9aqsEo1I9b5I20kA_12, "255", 3);
NIM_CONST tyArray_nHXaesL0DJZHyVS07ARPRA TM_DOEFk8Ga9aqsEo1I9b5I20kA_11 = {((NimStringDesc*) &TM_DOEFk8Ga9aqsEo1I9b5I20kA_12)}
;
STRING_LITERAL(TM_DOEFk8Ga9aqsEo1I9b5I20kA_15, "done", 4);

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_NIMCALL(NF, clamp_MP3SGCxfFIDw6O0yuRRW0g)(NF x) {
	NF result;
	nimfr_("clamp", "filewrite.nim");
	result = (NF)0;
	nimln_(5, "filewrite.nim");
	{
		if (!(x < 0.0)) goto LA3_;
		result = 0.0;
	}
	goto LA1_;
	LA3_: ;
	{
		nimln_(7, "filewrite.nim");
		if (!(1.0000000000000000e+00 < x)) goto LA6_;
		result = 1.0000000000000000e+00;
	}
	goto LA1_;
	LA6_: ;
	{
		result = x;
	}
	LA1_: ;
	popFrame();
	return result;
}

N_NIMCALL(NI, to255_BuAG9bvAB6AGfXCWB7MgNVg)(NF x) {
	NI result;
	NF T1_;
	NF T2_;
	nimfr_("to255", "filewrite.nim");
	result = (NI)0;
	nimln_(13, "filewrite.nim");
	T1_ = (NF)0;
	T1_ = clamp_MP3SGCxfFIDw6O0yuRRW0g(x);
	T2_ = (NF)0;
	T2_ = pow(T1_, 1.0000000000000000e+00);
	result = ((NI) (((NF)(T2_) * (NF)(2.5500000000000000e+02))));
	popFrame();
	return result;
}

static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	copyMem_E1xtACub5WcDa3vbrIXbwgsystem(((void*) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
	(*dest).Sup.len += (*src).Sup.len;
}

static N_INLINE(void, pushSafePoint)(TSafePoint* s) {
	(*s).hasRaiseAction = NIM_FALSE;
	(*s).prev = excHandler_rqLlY5bs9atDw2OXYqJEn5g;
	excHandler_rqLlY5bs9atDw2OXYqJEn5g = s;
}

static N_INLINE(void, writeLine_rBQVO3cm3BhnA9aEFD7PG6Qfilewrite)(FILE* f, NimStringDesc** x, NI xLen_0) {
	nimfr_("writeLine", "sysio.nim");
	{
		NimStringDesc* i;
		NI i_2;
		i = (NimStringDesc*)0;
		nimln_(2078, "system.nim");
		i_2 = ((NI) 0);
		{
			nimln_(2079, "system.nim");
			while (1) {
				if (!(i_2 < xLen_0)) goto LA3;
				nimln_(2080, "system.nim");
				i = x[i_2];
				nimln_(259, "sysio.nim");
				write_c4mGyJBvK73pdM22jiweKQ(f, i);
				nimln_(2081, "system.nim");
				i_2 += ((NI) 1);
			} LA3: ;
		}
	}
	nimln_(260, "sysio.nim");
	write_c4mGyJBvK73pdM22jiweKQ(f, ((NimStringDesc*) &TM_DOEFk8Ga9aqsEo1I9b5I20kA_4));
	popFrame();
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (a <= i);
		if (!(T3_)) goto LA4_;
		T3_ = (i <= b);
		LA4_: ;
		if (!T3_) goto LA5_;
		result = i;
		goto BeforeRet_;
	}
	goto LA1_;
	LA5_: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void, popSafePoint)(void) {
	excHandler_rqLlY5bs9atDw2OXYqJEn5g = (*excHandler_rqLlY5bs9atDw2OXYqJEn5g).prev;
}

static N_INLINE(void, setFrame)(TFrame* s) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
}

N_NIMCALL(void, ppmFileWrite_U4eWJEq9cgGb7B1ka9avleMw)(NimStringDesc* fileName, tyArray_9bH8Ed9bT7Ap1KqYu3IKfp4Q img) {
	FILE* f;
	NimStringDesc* T1_;
	NI width;
	NI height;
	TSafePoint TM_DOEFk8Ga9aqsEo1I9b5I20kA_3;
	nimfr_("ppmFileWrite", "filewrite.nim");
	nimln_(18, "filewrite.nim");
	T1_ = (NimStringDesc*)0;
	T1_ = rawNewString(fileName->Sup.len + 4);
appendString(T1_, ((NimStringDesc*) &TM_DOEFk8Ga9aqsEo1I9b5I20kA_2));
appendString(T1_, fileName);
	f = open_hqzpWQbdA2B8l9a6wwNoP4g(T1_, ((tyEnum_FileMode_fVUBHvW79bXUw1j55Oo9avSQ) 1), ((NI) -1));
	nimln_(19, "filewrite.nim");
	width = ((NI) 512);
	nimln_(20, "filewrite.nim");
	height = ((NI) 512);
	nimln_(21, "filewrite.nim");
	pushSafePoint(&TM_DOEFk8Ga9aqsEo1I9b5I20kA_3);
	TM_DOEFk8Ga9aqsEo1I9b5I20kA_3.status = _setjmp(TM_DOEFk8Ga9aqsEo1I9b5I20kA_3.context);
	if (TM_DOEFk8Ga9aqsEo1I9b5I20kA_3.status == 0) {
		tyArray_nHXaesL0DJZHyVS07ARPRA T3_;
		NimStringDesc* T4_;
		NimStringDesc* T5_;
		NimStringDesc* T6_;
		tyArray_nHXaesL0DJZHyVS07ARPRA T7_;
		NimStringDesc* T8_;
		NimStringDesc* T9_;
		NimStringDesc* T10_;
		nimln_(24, "filewrite.nim");
		writeLine_rBQVO3cm3BhnA9aEFD7PG6Qfilewrite(f, TM_DOEFk8Ga9aqsEo1I9b5I20kA_5, 1);
		nimln_(25, "filewrite.nim");
		memset((void*)T3_, 0, sizeof(T3_));
		T4_ = (NimStringDesc*)0;
		T5_ = (NimStringDesc*)0;
		T5_ = nimIntToStr(width);
		T6_ = (NimStringDesc*)0;
		T6_ = nimIntToStr(height);
		T4_ = rawNewString(T5_->Sup.len + T6_->Sup.len + 102);
appendString(T4_, ((NimStringDesc*) &TM_DOEFk8Ga9aqsEo1I9b5I20kA_7));
appendString(T4_, T5_);
appendString(T4_, ((NimStringDesc*) &TM_DOEFk8Ga9aqsEo1I9b5I20kA_8));
appendString(T4_, T6_);
appendString(T4_, ((NimStringDesc*) &TM_DOEFk8Ga9aqsEo1I9b5I20kA_9));
		T3_[0] = T4_;
		writeLine_rBQVO3cm3BhnA9aEFD7PG6Qfilewrite(f, T3_, 1);
		nimln_(26, "filewrite.nim");
		memset((void*)T7_, 0, sizeof(T7_));
		T8_ = (NimStringDesc*)0;
		T9_ = (NimStringDesc*)0;
		T9_ = nimIntToStr(width);
		T10_ = (NimStringDesc*)0;
		T10_ = nimIntToStr(height);
		T8_ = rawNewString(T9_->Sup.len + T10_->Sup.len + 1);
appendString(T8_, T9_);
appendString(T8_, ((NimStringDesc*) &TM_DOEFk8Ga9aqsEo1I9b5I20kA_10));
appendString(T8_, T10_);
		T7_[0] = T8_;
		writeLine_rBQVO3cm3BhnA9aEFD7PG6Qfilewrite(f, T7_, 1);
		nimln_(27, "filewrite.nim");
		writeLine_rBQVO3cm3BhnA9aEFD7PG6Qfilewrite(f, TM_DOEFk8Ga9aqsEo1I9b5I20kA_11, 1);
		{
			NI y;
			NI volatile res;
			y = (NI)0;
			nimln_(1986, "system.nim");
			res = ((NI) 0);
			{
				nimln_(1987, "system.nim");
				while (1) {
					NI TM_DOEFk8Ga9aqsEo1I9b5I20kA_14;
					if (!(res <= ((NI) 511))) goto LA13;
					nimln_(1988, "system.nim");
					y = ((NI)chckRange(res, ((NI) 0), ((NI) 511)));
					{
						NI x;
						NI volatile res_2;
						x = (NI)0;
						nimln_(1986, "system.nim");
						res_2 = ((NI) 0);
						{
							nimln_(1987, "system.nim");
							while (1) {
								tyArray_nHXaesL0DJZHyVS07ARPRA T17_;
								NimStringDesc* T18_;
								NI T19_;
								NimStringDesc* T20_;
								NI T21_;
								NimStringDesc* T22_;
								NI T23_;
								NimStringDesc* T24_;
								NI TM_DOEFk8Ga9aqsEo1I9b5I20kA_13;
								if (!(res_2 <= ((NI) 511))) goto LA16;
								nimln_(1988, "system.nim");
								x = ((NI)chckRange(res_2, ((NI) 0), ((NI) 511)));
								nimln_(30, "filewrite.nim");
								memset((void*)T17_, 0, sizeof(T17_));
								T18_ = (NimStringDesc*)0;
								T19_ = (NI)0;
								T19_ = to255_BuAG9bvAB6AGfXCWB7MgNVg(img[(x)- 0][(y)- 0][(((NI) 0))- 0]);
								T20_ = (NimStringDesc*)0;
								T20_ = nimIntToStr(T19_);
								T21_ = (NI)0;
								T21_ = to255_BuAG9bvAB6AGfXCWB7MgNVg(-(img[(x)- 0][(y)- 0][(((NI) 1))- 0]));
								T22_ = (NimStringDesc*)0;
								T22_ = nimIntToStr(T21_);
								T23_ = (NI)0;
								T23_ = to255_BuAG9bvAB6AGfXCWB7MgNVg(img[(x)- 0][(y)- 0][(((NI) 2))- 0]);
								T24_ = (NimStringDesc*)0;
								T24_ = nimIntToStr(T23_);
								T18_ = rawNewString(T20_->Sup.len + T22_->Sup.len + T24_->Sup.len + 2);
appendString(T18_, T20_);
appendString(T18_, ((NimStringDesc*) &TM_DOEFk8Ga9aqsEo1I9b5I20kA_10));
appendString(T18_, T22_);
appendString(T18_, ((NimStringDesc*) &TM_DOEFk8Ga9aqsEo1I9b5I20kA_10));
appendString(T18_, T24_);
								T17_[0] = T18_;
								writeLine_rBQVO3cm3BhnA9aEFD7PG6Qfilewrite(f, T17_, 1);
								nimln_(1989, "system.nim");
								TM_DOEFk8Ga9aqsEo1I9b5I20kA_13 = addInt(res_2, ((NI) 1));
								res_2 = (NI)(TM_DOEFk8Ga9aqsEo1I9b5I20kA_13);
							} LA16: ;
						}
					}
					TM_DOEFk8Ga9aqsEo1I9b5I20kA_14 = addInt(res, ((NI) 1));
					res = (NI)(TM_DOEFk8Ga9aqsEo1I9b5I20kA_14);
				} LA13: ;
			}
		}
		popSafePoint();
	}
	else {
		popSafePoint();
		setFrame((TFrame*)&FR_);
	}
	{
		nimln_(22, "filewrite.nim");
		close_BWnr8V7RERYno9bIdPmw8Hw_2(f);
		nimln_(23, "filewrite.nim");
		printf("%s\012", ((NimStringDesc*) &TM_DOEFk8Ga9aqsEo1I9b5I20kA_15)? (((NimStringDesc*) &TM_DOEFk8Ga9aqsEo1I9b5I20kA_15))->data:"nil");
		fflush(stdout);
	}
	if (TM_DOEFk8Ga9aqsEo1I9b5I20kA_3.status != 0) reraiseException();
	popFrame();
}
NIM_EXTERNC N_NOINLINE(void, unknown_filewriteInit000)(void) {
	nimfr_("filewrite", "filewrite.nim");
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, unknown_filewriteDatInit000)(void) {
}

