/* Generated by Nim Compiler v0.17.2 */
/*   (c) 2017 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w  -I/usr/local/Cellar/nim/0.17.2/nim/lib -o /Users/nao/Documents/ray/nim-ray/nimcache/smallpt.o /Users/nao/Documents/ray/nim-ray/nimcache/smallpt.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <math.h>
#include <stdio.h>
#include <setjmp.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyObject_SpherecolonObjectType__yBoRCES4Zo89cGXl1w5XsLg tyObject_SpherecolonObjectType__yBoRCES4Zo89cGXl1w5XsLg;
typedef struct tyObject_RaycolonObjectType__LVquPCLWyCZwXDkBjs9aUbQ tyObject_RaycolonObjectType__LVquPCLWyCZwXDkBjs9aUbQ;
typedef struct RootObj RootObj;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct Exception Exception;
typedef struct TSafePoint TSafePoint;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NF tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ[3];
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
struct RootObj {
TNimType* m_type;
};
typedef NU8 tyEnum_Reflection_2FjKZ9aXFuKwq380tULF9cAA;
struct tyObject_SpherecolonObjectType__yBoRCES4Zo89cGXl1w5XsLg {
  RootObj Sup;
NF rad;
tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ pos;
tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ emi;
tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ col;
tyEnum_Reflection_2FjKZ9aXFuKwq380tULF9cAA refl;
};
struct tyObject_RaycolonObjectType__LVquPCLWyCZwXDkBjs9aUbQ {
  RootObj Sup;
tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ o;
tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ d;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef NI tyArray_Bd4h7Ocx9bGTvrKzPIWNlHw[3];
typedef tyArray_Bd4h7Ocx9bGTvrKzPIWNlHw tyArray_niNEKVbrl40V4VyYBRDvTw[11];
typedef tyArray_niNEKVbrl40V4VyYBRDvTw tyArray_9cP2t1NHU9aFZ42YRZQf8QtA[16];
typedef NU8 tyEnum_FileMode_fVUBHvW79bXUw1j55Oo9avSQ;
struct Exception {
  RootObj Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
Exception* up;
};
typedef struct {
N_NIMCALL_PTR(NIM_BOOL, ClP_0) (Exception* e, void* ClE_0);
void* ClE_0;
} tyProc_KeeAOYBd84Ofsw6Y7LizaQ;
struct TSafePoint {
TSafePoint* prev;
NI status;
jmp_buf context;
NIM_BOOL hasRaiseAction;
tyProc_KeeAOYBd84Ofsw6Y7LizaQ raiseAction;
};
typedef NimStringDesc* tyArray_nHXaesL0DJZHyVS07ARPRA[1];
N_NIMCALL(NimStringDesc*, dollar__c63ljC9b6G8Cx2lEZrZbhGg)(tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ a);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size);
N_NIMCALL(NimStringDesc*, nimFloatToStr)(NF f);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(void, plus__eFhOTkO0DjxYCcDDmGVpZw)(tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ left, tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ right, tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ Result);
N_NIMCALL(void, minus__eFhOTkO0DjxYCcDDmGVpZw_2)(tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ left, tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ right, tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ Result);
N_NIMCALL(void, star__vK71ir6Xl8hGdrUe0HVDuw)(NF left, tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ right, tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ Result);
N_NIMCALL(void, star__nuweUnsbcP12PlMHax5oHA)(tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ left, NF right, tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ Result);
N_NIMCALL(NF, dot_6YBISxAR9cgd0EkOrE6ChCw)(tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ left, tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ right);
N_NIMCALL(void, cross_eFhOTkO0DjxYCcDDmGVpZw_3)(tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ left, tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ right, tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ Result);
N_NIMCALL(void, mult_eFhOTkO0DjxYCcDDmGVpZw_4)(tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ left, tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ right, tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ Result);
N_NIMCALL(NF, norm_QwSbIbEhPHN5Sm2SBUYnFg)(tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ this_0);
N_NIMCALL(void, normalize_pbr8jh9bm8VCjZwIw8q6gUA)(tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ this_0, tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ Result);
N_NIMCALL(NF, intersect_QoV0689bTIEotf1mp8V3Ewg)(tyObject_SpherecolonObjectType__yBoRCES4Zo89cGXl1w5XsLg* this_0, tyObject_RaycolonObjectType__LVquPCLWyCZwXDkBjs9aUbQ* r);
N_NOINLINE(void, chckNil)(void* p);
N_NIMCALL(void, genericReset)(void* dest, TNimType* mt);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
N_NIMCALL(NI, mulInt)(NI a, NI b);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(void, writeLine_rBQVO3cm3BhnA9aEFD7PG6Qsmallpt)(FILE* f, NimStringDesc** x, NI xLen_0);
N_NIMCALL(void, write_c4mGyJBvK73pdM22jiweKQ)(FILE* f, NimStringDesc* s);
N_NIMCALL(FILE*, open_hqzpWQbdA2B8l9a6wwNoP4g)(NimStringDesc* filename, tyEnum_FileMode_fVUBHvW79bXUw1j55Oo9avSQ mode, NI bufSize);
static N_INLINE(void, pushSafePoint)(TSafePoint* s);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x);
static N_INLINE(void, popSafePoint)(void);
static N_INLINE(void, setFrame)(TFrame* s);
N_NIMCALL(void, close_BWnr8V7RERYno9bIdPmw8Hw_2)(FILE* f);
N_NIMCALL(void, reraiseException)(void);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* theStackBottom);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void);
NIM_EXTERNC N_NOINLINE(void, smallptDatInit000)(void);
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ a_EaNEtO3p25Ff3IlC4UQzeA;
tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ b_bRWRVurYeZESZQXlYiK9cBw;
tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ x_SUqsDotgvTqFCNUeIbepAw;
tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ y_VWWbeGgYGRhL7HoMsfa4Yg;
tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ c_fSDYKN4bfPLcJXAVgS4rxA;
extern TNimType NTI_w9bl9a1ul9ctRJWiMl9cNnIMvg_;
TNimType NTI_9ce69c9a1NzlPVqY9aKHS79b5IQ_;
tyArray_9cP2t1NHU9aFZ42YRZQf8QtA img_PW8HahrrKxSsH24BoBt9aFg;
NI i_6no7U3LksouOW9cjgQmL27w;
NI j_gF9ar53guqMqheiPMKOEaAg;
FILE* f_y7t9aVv0a58PJGWzUFhhDSA;
extern TSafePoint* excHandler_rqLlY5bs9atDw2OXYqJEn5g;
NI i_6no7U3LksouOW9cjgQmL27w_2;
NI j_gF9ar53guqMqheiPMKOEaAg_2;
STRING_LITERAL(TM_FYzz9bEDZQEsPJ4L9bzzDvVw_2, "[", 1);
STRING_LITERAL(TM_FYzz9bEDZQEsPJ4L9bzzDvVw_3, ", ", 2);
STRING_LITERAL(TM_FYzz9bEDZQEsPJ4L9bzzDvVw_4, "]", 1);
NIM_CONST tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ TM_FYzz9bEDZQEsPJ4L9bzzDvVw_5 = {1.0000000000000000e+00,
2.0000000000000000e+00,
3.0000000000000000e+00}
;
NIM_CONST tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ TM_FYzz9bEDZQEsPJ4L9bzzDvVw_6 = {2.0000000000000000e+00,
4.0000000000000000e+00,
2.0000000000000000e+00}
;
NIM_CONST tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ TM_FYzz9bEDZQEsPJ4L9bzzDvVw_7 = {4.0000000000000000e+00,
1.0000000000000000e+00,
2.0000000000000000e+00}
;
STRING_LITERAL(TM_FYzz9bEDZQEsPJ4L9bzzDvVw_14, "\012", 1);
STRING_LITERAL(TM_FYzz9bEDZQEsPJ4L9bzzDvVw_15, "img.ppm", 7);
STRING_LITERAL(TM_FYzz9bEDZQEsPJ4L9bzzDvVw_18, "P3", 2);
NIM_CONST tyArray_nHXaesL0DJZHyVS07ARPRA TM_FYzz9bEDZQEsPJ4L9bzzDvVw_17 = {((NimStringDesc*) &TM_FYzz9bEDZQEsPJ4L9bzzDvVw_18)}
;
STRING_LITERAL(TM_FYzz9bEDZQEsPJ4L9bzzDvVw_20, "# The P3 means colors are in ASCII, then 15 columns and 10 rows"
", then 255 for max color, then RGB triplets", 106);
NIM_CONST tyArray_nHXaesL0DJZHyVS07ARPRA TM_FYzz9bEDZQEsPJ4L9bzzDvVw_19 = {((NimStringDesc*) &TM_FYzz9bEDZQEsPJ4L9bzzDvVw_20)}
;
STRING_LITERAL(TM_FYzz9bEDZQEsPJ4L9bzzDvVw_22, "15 10", 5);
NIM_CONST tyArray_nHXaesL0DJZHyVS07ARPRA TM_FYzz9bEDZQEsPJ4L9bzzDvVw_21 = {((NimStringDesc*) &TM_FYzz9bEDZQEsPJ4L9bzzDvVw_22)}
;
STRING_LITERAL(TM_FYzz9bEDZQEsPJ4L9bzzDvVw_24, "255", 3);
NIM_CONST tyArray_nHXaesL0DJZHyVS07ARPRA TM_FYzz9bEDZQEsPJ4L9bzzDvVw_23 = {((NimStringDesc*) &TM_FYzz9bEDZQEsPJ4L9bzzDvVw_24)}
;
STRING_LITERAL(TM_FYzz9bEDZQEsPJ4L9bzzDvVw_25, " ", 1);
STRING_LITERAL(TM_FYzz9bEDZQEsPJ4L9bzzDvVw_28, "closed", 6);

static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	copyMem_E1xtACub5WcDa3vbrIXbwgsystem(((void*) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
	(*dest).Sup.len += (*src).Sup.len;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_NIMCALL(NimStringDesc*, dollar__c63ljC9b6G8Cx2lEZrZbhGg)(tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ a) {
	NimStringDesc* result;
	NimStringDesc* T1_;
	NimStringDesc* T2_;
	NimStringDesc* T3_;
	NimStringDesc* T4_;
	nimfr_("$", "smallpt.nim");
	result = (NimStringDesc*)0;
	nimln_(6, "smallpt.nim");
	T1_ = (NimStringDesc*)0;
	T2_ = (NimStringDesc*)0;
	T2_ = nimFloatToStr(a[(((NI) 0))- 0]);
	T3_ = (NimStringDesc*)0;
	T3_ = nimFloatToStr(a[(((NI) 1))- 0]);
	T4_ = (NimStringDesc*)0;
	T4_ = nimFloatToStr(a[(((NI) 2))- 0]);
	T1_ = rawNewString(T2_->Sup.len + T3_->Sup.len + T4_->Sup.len + 6);
appendString(T1_, ((NimStringDesc*) &TM_FYzz9bEDZQEsPJ4L9bzzDvVw_2));
appendString(T1_, T2_);
appendString(T1_, ((NimStringDesc*) &TM_FYzz9bEDZQEsPJ4L9bzzDvVw_3));
appendString(T1_, T3_);
appendString(T1_, ((NimStringDesc*) &TM_FYzz9bEDZQEsPJ4L9bzzDvVw_3));
appendString(T1_, T4_);
appendString(T1_, ((NimStringDesc*) &TM_FYzz9bEDZQEsPJ4L9bzzDvVw_4));
	result = T1_;
	popFrame();
	return result;
}

N_NIMCALL(void, plus__eFhOTkO0DjxYCcDDmGVpZw)(tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ left, tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ right, tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ Result) {
	nimfr_("+", "smallpt.nim");
	nimln_(9, "smallpt.nim");
	Result[0] = ((NF)(left[(((NI) 0))- 0]) + (NF)(right[(((NI) 0))- 0]));
	Result[1] = ((NF)(left[(((NI) 1))- 0]) + (NF)(right[(((NI) 1))- 0]));
	Result[2] = ((NF)(left[(((NI) 2))- 0]) + (NF)(right[(((NI) 2))- 0]));
	popFrame();
}

N_NIMCALL(void, minus__eFhOTkO0DjxYCcDDmGVpZw_2)(tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ left, tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ right, tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ Result) {
	nimfr_("-", "smallpt.nim");
	nimln_(12, "smallpt.nim");
	Result[0] = ((NF)(left[(((NI) 0))- 0]) - (NF)(right[(((NI) 0))- 0]));
	Result[1] = ((NF)(left[(((NI) 1))- 0]) - (NF)(right[(((NI) 1))- 0]));
	Result[2] = ((NF)(left[(((NI) 2))- 0]) - (NF)(right[(((NI) 2))- 0]));
	popFrame();
}

N_NIMCALL(void, star__vK71ir6Xl8hGdrUe0HVDuw)(NF left, tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ right, tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ Result) {
	nimfr_("*", "smallpt.nim");
	nimln_(15, "smallpt.nim");
	Result[0] = ((NF)(left) * (NF)(right[(((NI) 0))- 0]));
	Result[1] = ((NF)(left) * (NF)(right[(((NI) 1))- 0]));
	Result[2] = ((NF)(left) * (NF)(right[(((NI) 2))- 0]));
	popFrame();
}

N_NIMCALL(void, star__nuweUnsbcP12PlMHax5oHA)(tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ left, NF right, tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ Result) {
	nimfr_("*", "smallpt.nim");
	nimln_(18, "smallpt.nim");
	Result[0] = ((NF)(left[(((NI) 0))- 0]) * (NF)(right));
	Result[1] = ((NF)(left[(((NI) 1))- 0]) * (NF)(right));
	Result[2] = ((NF)(left[(((NI) 2))- 0]) * (NF)(right));
	popFrame();
}

N_NIMCALL(NF, dot_6YBISxAR9cgd0EkOrE6ChCw)(tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ left, tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ right) {
	NF result;
	nimfr_("dot", "smallpt.nim");
	result = (NF)0;
	nimln_(21, "smallpt.nim");
	result = ((NF)(((NF)(((NF)(left[(((NI) 0))- 0]) * (NF)(right[(((NI) 0))- 0]))) + (NF)(((NF)(left[(((NI) 1))- 0]) * (NF)(right[(((NI) 1))- 0]))))) + (NF)(((NF)(left[(((NI) 2))- 0]) * (NF)(right[(((NI) 2))- 0]))));
	popFrame();
	return result;
}

N_NIMCALL(void, cross_eFhOTkO0DjxYCcDDmGVpZw_3)(tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ left, tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ right, tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ Result) {
	nimfr_("cross", "smallpt.nim");
	nimln_(24, "smallpt.nim");
	Result[0] = ((NF)(left[(((NI) 0))- 0]) - (NF)(right[(((NI) 0))- 0]));
	Result[1] = ((NF)(left[(((NI) 1))- 0]) - (NF)(right[(((NI) 1))- 0]));
	Result[2] = ((NF)(left[(((NI) 2))- 0]) - (NF)(right[(((NI) 2))- 0]));
	popFrame();
}

N_NIMCALL(void, mult_eFhOTkO0DjxYCcDDmGVpZw_4)(tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ left, tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ right, tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ Result) {
	nimfr_("mult", "smallpt.nim");
	nimln_(27, "smallpt.nim");
	Result[0] = ((NF)(left[(((NI) 0))- 0]) * (NF)(right[(((NI) 0))- 0]));
	Result[1] = ((NF)(left[(((NI) 1))- 0]) * (NF)(right[(((NI) 1))- 0]));
	Result[2] = ((NF)(left[(((NI) 2))- 0]) * (NF)(right[(((NI) 2))- 0]));
	popFrame();
}

N_NIMCALL(NF, norm_QwSbIbEhPHN5Sm2SBUYnFg)(tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ this_0) {
	NF result;
	NF T1_;
	nimfr_("norm", "smallpt.nim");
	result = (NF)0;
	nimln_(30, "smallpt.nim");
	T1_ = (NF)0;
	T1_ = dot_6YBISxAR9cgd0EkOrE6ChCw(this_0, this_0);
	result = sqrt(T1_);
	popFrame();
	return result;
}

N_NIMCALL(void, normalize_pbr8jh9bm8VCjZwIw8q6gUA)(tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ this_0, tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ Result) {
	NF T1_;
	tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ T2_;
	nimfr_("normalize", "smallpt.nim");
	nimln_(33, "smallpt.nim");
	T1_ = (NF)0;
	T1_ = norm_QwSbIbEhPHN5Sm2SBUYnFg(this_0);
	memset((void*)T2_, 0, sizeof(T2_));
	star__nuweUnsbcP12PlMHax5oHA(this_0, ((NF)(1.0000000000000000e+00) / (NF)(T1_)), T2_);
	memcpy((void*)Result, (NIM_CONST void*)T2_, sizeof(tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ));
	popFrame();
}

N_NIMCALL(NF, intersect_QoV0689bTIEotf1mp8V3Ewg)(tyObject_SpherecolonObjectType__yBoRCES4Zo89cGXl1w5XsLg* this_0, tyObject_RaycolonObjectType__LVquPCLWyCZwXDkBjs9aUbQ* r) {
	NF result;
	tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ op;
	tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ T1_;
	NF t;
	NF eps;
	NF b;
	NF det;
	NF T2_;
	nimfr_("intersect", "smallpt.nim");
{	result = (NF)0;
	memset((void*)op, 0, sizeof(op));
	nimln_(67, "smallpt.nim");
	memset((void*)T1_, 0, sizeof(T1_));
	minus__eFhOTkO0DjxYCcDDmGVpZw_2((*this_0).pos, (*r).o, T1_);
	memcpy((void*)op, (NIM_CONST void*)T1_, sizeof(tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ));
	t = (NF)0;
	nimln_(70, "smallpt.nim");
	eps = 1.0000000000000000e-04;
	nimln_(71, "smallpt.nim");
	b = dot_6YBISxAR9cgd0EkOrE6ChCw(op, (*r).d);
	nimln_(72, "smallpt.nim");
	T2_ = (NF)0;
	T2_ = norm_QwSbIbEhPHN5Sm2SBUYnFg(op);
	det = ((NF)(((NF)(((NF)(b) * (NF)(b))) - (NF)(T2_))) + (NF)(((NF)((*this_0).rad) * (NF)((*this_0).rad))));
	nimln_(73, "smallpt.nim");
	{
		if (!(det < 0.0)) goto LA5_;
		nimln_(74, "smallpt.nim");
		result = 0.0;
		goto BeforeRet_;
	}
	goto LA3_;
	LA5_: ;
	{
		nimln_(76, "smallpt.nim");
		det = sqrt(det);
	}
	LA3_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (a <= i);
		if (!(T3_)) goto LA4_;
		T3_ = (i <= b);
		LA4_: ;
		if (!T3_) goto LA5_;
		result = i;
		goto BeforeRet_;
	}
	goto LA1_;
	LA5_: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void, writeLine_rBQVO3cm3BhnA9aEFD7PG6Qsmallpt)(FILE* f, NimStringDesc** x, NI xLen_0) {
	nimfr_("writeLine", "sysio.nim");
	{
		NimStringDesc* i;
		NI i_2;
		i = (NimStringDesc*)0;
		nimln_(2078, "system.nim");
		i_2 = ((NI) 0);
		{
			nimln_(2079, "system.nim");
			while (1) {
				if (!(i_2 < xLen_0)) goto LA3;
				nimln_(2080, "system.nim");
				i = x[i_2];
				nimln_(259, "sysio.nim");
				write_c4mGyJBvK73pdM22jiweKQ(f, i);
				nimln_(2081, "system.nim");
				i_2 += ((NI) 1);
			} LA3: ;
		}
	}
	nimln_(260, "sysio.nim");
	write_c4mGyJBvK73pdM22jiweKQ(f, ((NimStringDesc*) &TM_FYzz9bEDZQEsPJ4L9bzzDvVw_14));
	popFrame();
}

static N_INLINE(void, pushSafePoint)(TSafePoint* s) {
	(*s).hasRaiseAction = NIM_FALSE;
	(*s).prev = excHandler_rqLlY5bs9atDw2OXYqJEn5g;
	excHandler_rqLlY5bs9atDw2OXYqJEn5g = s;
}

static N_INLINE(void, popSafePoint)(void) {
	excHandler_rqLlY5bs9atDw2OXYqJEn5g = (*excHandler_rqLlY5bs9atDw2OXYqJEn5g).prev;
}

static N_INLINE(void, setFrame)(TFrame* s) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
}

N_NIMCALL(NF, intersect_XmtE9b553rWm1NbrP567yDA)(tyObject_SpherecolonObjectType__yBoRCES4Zo89cGXl1w5XsLg* this_0, tyObject_RaycolonObjectType__LVquPCLWyCZwXDkBjs9aUbQ* r) {
	NF result;
	nimfr_("intersect", "smallpt.nim");
{	result = (NF)0;
	nimln_(66, "smallpt.nim");
	result = intersect_QoV0689bTIEotf1mp8V3Ewg(this_0, r);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner(void) {
	systemInit000();
	stdlib_mathDatInit000();
	smallptDatInit000();
	stdlib_mathInit000();
}

void PreMain(void) {
	void (*volatile inner)(void);
	systemDatInit000();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void) {
	tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ T1_;
	NimStringDesc* T2_;
	tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ T3_;
	NimStringDesc* T4_;
	tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ T5_;
	NimStringDesc* T6_;
	tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ T7_;
	NimStringDesc* T8_;
	NF T9_;
	NimStringDesc* T10_;
	tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ T11_;
	NimStringDesc* T12_;
	tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ T13_;
	NimStringDesc* T14_;
	NF T15_;
	NimStringDesc* T16_;
	tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ T17_;
	NimStringDesc* T18_;
	NimStringDesc* T19_;
	nimfr_("smallpt", "smallpt.nim");
	nimln_(36, "smallpt.nim");
	memcpy((void*)a_EaNEtO3p25Ff3IlC4UQzeA, (NIM_CONST void*)TM_FYzz9bEDZQEsPJ4L9bzzDvVw_5, sizeof(tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ));
	nimln_(37, "smallpt.nim");
	memcpy((void*)b_bRWRVurYeZESZQXlYiK9cBw, (NIM_CONST void*)TM_FYzz9bEDZQEsPJ4L9bzzDvVw_6, sizeof(tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ));
	nimln_(39, "smallpt.nim");
	memset((void*)T1_, 0, sizeof(T1_));
	plus__eFhOTkO0DjxYCcDDmGVpZw(a_EaNEtO3p25Ff3IlC4UQzeA, b_bRWRVurYeZESZQXlYiK9cBw, T1_);
	T2_ = (NimStringDesc*)0;
	T2_ = dollar__c63ljC9b6G8Cx2lEZrZbhGg(T1_);
	printf("%s\012", T2_? (T2_)->data:"nil");
	fflush(stdout);
	nimln_(40, "smallpt.nim");
	memset((void*)T3_, 0, sizeof(T3_));
	minus__eFhOTkO0DjxYCcDDmGVpZw_2(a_EaNEtO3p25Ff3IlC4UQzeA, b_bRWRVurYeZESZQXlYiK9cBw, T3_);
	T4_ = (NimStringDesc*)0;
	T4_ = dollar__c63ljC9b6G8Cx2lEZrZbhGg(T3_);
	printf("%s\012", T4_? (T4_)->data:"nil");
	fflush(stdout);
	nimln_(41, "smallpt.nim");
	memset((void*)T5_, 0, sizeof(T5_));
	star__nuweUnsbcP12PlMHax5oHA(a_EaNEtO3p25Ff3IlC4UQzeA, 4.0000000000000000e+00, T5_);
	T6_ = (NimStringDesc*)0;
	T6_ = dollar__c63ljC9b6G8Cx2lEZrZbhGg(T5_);
	printf("%s\012", T6_? (T6_)->data:"nil");
	fflush(stdout);
	nimln_(42, "smallpt.nim");
	memset((void*)T7_, 0, sizeof(T7_));
	star__vK71ir6Xl8hGdrUe0HVDuw(4.0000000000000000e+00, b_bRWRVurYeZESZQXlYiK9cBw, T7_);
	T8_ = (NimStringDesc*)0;
	T8_ = dollar__c63ljC9b6G8Cx2lEZrZbhGg(T7_);
	printf("%s\012", T8_? (T8_)->data:"nil");
	fflush(stdout);
	nimln_(43, "smallpt.nim");
	T9_ = (NF)0;
	T9_ = dot_6YBISxAR9cgd0EkOrE6ChCw(a_EaNEtO3p25Ff3IlC4UQzeA, b_bRWRVurYeZESZQXlYiK9cBw);
	T10_ = (NimStringDesc*)0;
	T10_ = nimFloatToStr(T9_);
	printf("%s\012", T10_? (T10_)->data:"nil");
	fflush(stdout);
	nimln_(44, "smallpt.nim");
	memset((void*)T11_, 0, sizeof(T11_));
	cross_eFhOTkO0DjxYCcDDmGVpZw_3(a_EaNEtO3p25Ff3IlC4UQzeA, b_bRWRVurYeZESZQXlYiK9cBw, T11_);
	T12_ = (NimStringDesc*)0;
	T12_ = dollar__c63ljC9b6G8Cx2lEZrZbhGg(T11_);
	printf("%s\012", T12_? (T12_)->data:"nil");
	fflush(stdout);
	nimln_(45, "smallpt.nim");
	memset((void*)T13_, 0, sizeof(T13_));
	mult_eFhOTkO0DjxYCcDDmGVpZw_4(a_EaNEtO3p25Ff3IlC4UQzeA, b_bRWRVurYeZESZQXlYiK9cBw, T13_);
	T14_ = (NimStringDesc*)0;
	T14_ = dollar__c63ljC9b6G8Cx2lEZrZbhGg(T13_);
	printf("%s\012", T14_? (T14_)->data:"nil");
	fflush(stdout);
	nimln_(46, "smallpt.nim");
	T15_ = (NF)0;
	T15_ = norm_QwSbIbEhPHN5Sm2SBUYnFg(a_EaNEtO3p25Ff3IlC4UQzeA);
	T16_ = (NimStringDesc*)0;
	T16_ = nimFloatToStr(T15_);
	printf("%s\012", T16_? (T16_)->data:"nil");
	fflush(stdout);
	nimln_(47, "smallpt.nim");
	memset((void*)T17_, 0, sizeof(T17_));
	normalize_pbr8jh9bm8VCjZwIw8q6gUA(a_EaNEtO3p25Ff3IlC4UQzeA, T17_);
	T18_ = (NimStringDesc*)0;
	T18_ = dollar__c63ljC9b6G8Cx2lEZrZbhGg(T17_);
	printf("%s\012", T18_? (T18_)->data:"nil");
	fflush(stdout);
	nimln_(78, "smallpt.nim");
	memcpy((void*)x_SUqsDotgvTqFCNUeIbepAw, (NIM_CONST void*)TM_FYzz9bEDZQEsPJ4L9bzzDvVw_5, sizeof(tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ));
	nimln_(79, "smallpt.nim");
	memcpy((void*)y_VWWbeGgYGRhL7HoMsfa4Yg, (NIM_CONST void*)TM_FYzz9bEDZQEsPJ4L9bzzDvVw_7, sizeof(tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ));
	nimln_(81, "smallpt.nim");
	chckNil((void*)c_fSDYKN4bfPLcJXAVgS4rxA);
	genericReset((void*)c_fSDYKN4bfPLcJXAVgS4rxA, (&NTI_9ce69c9a1NzlPVqY9aKHS79b5IQ_));
	mult_eFhOTkO0DjxYCcDDmGVpZw_4(x_SUqsDotgvTqFCNUeIbepAw, y_VWWbeGgYGRhL7HoMsfa4Yg, c_fSDYKN4bfPLcJXAVgS4rxA);
	nimln_(83, "smallpt.nim");
	T19_ = (NimStringDesc*)0;
	T19_ = dollar__c63ljC9b6G8Cx2lEZrZbhGg(c_fSDYKN4bfPLcJXAVgS4rxA);
	printf("%s\012", T19_? (T19_)->data:"nil");
	fflush(stdout);
	{
		NI res;
		nimln_(1986, "system.nim");
		res = ((NI) 0);
		{
			nimln_(1987, "system.nim");
			while (1) {
				NI TM_FYzz9bEDZQEsPJ4L9bzzDvVw_13;
				if (!(res <= ((NI) 15))) goto LA22;
				nimln_(1988, "system.nim");
				i_6no7U3LksouOW9cjgQmL27w = ((NI)chckRange(res, ((NI) 0), ((NI) 15)));
				{
					NI res_2;
					j_gF9ar53guqMqheiPMKOEaAg = 0;
					nimln_(1986, "system.nim");
					res_2 = ((NI) 0);
					{
						nimln_(1987, "system.nim");
						while (1) {
							NI TM_FYzz9bEDZQEsPJ4L9bzzDvVw_8;
							NI TM_FYzz9bEDZQEsPJ4L9bzzDvVw_9;
							NI TM_FYzz9bEDZQEsPJ4L9bzzDvVw_10;
							NI TM_FYzz9bEDZQEsPJ4L9bzzDvVw_11;
							NI TM_FYzz9bEDZQEsPJ4L9bzzDvVw_12;
							if (!(res_2 <= ((NI) 10))) goto LA25;
							nimln_(1988, "system.nim");
							j_gF9ar53guqMqheiPMKOEaAg = ((NI)chckRange(res_2, ((NI) 0), ((NI) 10)));
							nimln_(92, "smallpt.nim");
							TM_FYzz9bEDZQEsPJ4L9bzzDvVw_8 = mulInt(((NI) (i_6no7U3LksouOW9cjgQmL27w)), ((NI) 10));
							img_PW8HahrrKxSsH24BoBt9aFg[(i_6no7U3LksouOW9cjgQmL27w)- 0][(j_gF9ar53guqMqheiPMKOEaAg)- 0][0] = ((NI) ((NI)(TM_FYzz9bEDZQEsPJ4L9bzzDvVw_8)));
							TM_FYzz9bEDZQEsPJ4L9bzzDvVw_9 = mulInt(((NI) (j_gF9ar53guqMqheiPMKOEaAg)), ((NI) 10));
							img_PW8HahrrKxSsH24BoBt9aFg[(i_6no7U3LksouOW9cjgQmL27w)- 0][(j_gF9ar53guqMqheiPMKOEaAg)- 0][1] = ((NI) ((NI)(TM_FYzz9bEDZQEsPJ4L9bzzDvVw_9)));
							TM_FYzz9bEDZQEsPJ4L9bzzDvVw_10 = addInt(((NI) (i_6no7U3LksouOW9cjgQmL27w)), ((NI) (j_gF9ar53guqMqheiPMKOEaAg)));
							TM_FYzz9bEDZQEsPJ4L9bzzDvVw_11 = mulInt(((NI) ((NI)(TM_FYzz9bEDZQEsPJ4L9bzzDvVw_10))), ((NI) 10));
							img_PW8HahrrKxSsH24BoBt9aFg[(i_6no7U3LksouOW9cjgQmL27w)- 0][(j_gF9ar53guqMqheiPMKOEaAg)- 0][2] = ((NI) ((NI)(TM_FYzz9bEDZQEsPJ4L9bzzDvVw_11)));
							nimln_(1989, "system.nim");
							TM_FYzz9bEDZQEsPJ4L9bzzDvVw_12 = addInt(res_2, ((NI) 1));
							res_2 = (NI)(TM_FYzz9bEDZQEsPJ4L9bzzDvVw_12);
						} LA25: ;
					}
				}
				TM_FYzz9bEDZQEsPJ4L9bzzDvVw_13 = addInt(res, ((NI) 1));
				res = (NI)(TM_FYzz9bEDZQEsPJ4L9bzzDvVw_13);
			} LA22: ;
		}
	}
	{
		TSafePoint TM_FYzz9bEDZQEsPJ4L9bzzDvVw_16;
		nimln_(95, "smallpt.nim");
		f_y7t9aVv0a58PJGWzUFhhDSA = open_hqzpWQbdA2B8l9a6wwNoP4g(((NimStringDesc*) &TM_FYzz9bEDZQEsPJ4L9bzzDvVw_15), ((tyEnum_FileMode_fVUBHvW79bXUw1j55Oo9avSQ) 1), ((NI) -1));
		nimln_(96, "smallpt.nim");
		pushSafePoint(&TM_FYzz9bEDZQEsPJ4L9bzzDvVw_16);
		TM_FYzz9bEDZQEsPJ4L9bzzDvVw_16.status = _setjmp(TM_FYzz9bEDZQEsPJ4L9bzzDvVw_16.context);
		if (TM_FYzz9bEDZQEsPJ4L9bzzDvVw_16.status == 0) {
			nimln_(99, "smallpt.nim");
			writeLine_rBQVO3cm3BhnA9aEFD7PG6Qsmallpt(f_y7t9aVv0a58PJGWzUFhhDSA, TM_FYzz9bEDZQEsPJ4L9bzzDvVw_17, 1);
			nimln_(100, "smallpt.nim");
			writeLine_rBQVO3cm3BhnA9aEFD7PG6Qsmallpt(f_y7t9aVv0a58PJGWzUFhhDSA, TM_FYzz9bEDZQEsPJ4L9bzzDvVw_19, 1);
			nimln_(101, "smallpt.nim");
			writeLine_rBQVO3cm3BhnA9aEFD7PG6Qsmallpt(f_y7t9aVv0a58PJGWzUFhhDSA, TM_FYzz9bEDZQEsPJ4L9bzzDvVw_21, 1);
			nimln_(102, "smallpt.nim");
			writeLine_rBQVO3cm3BhnA9aEFD7PG6Qsmallpt(f_y7t9aVv0a58PJGWzUFhhDSA, TM_FYzz9bEDZQEsPJ4L9bzzDvVw_23, 1);
			{
				NI volatile res_3;
				nimln_(1986, "system.nim");
				res_3 = ((NI) 0);
				{
					nimln_(1987, "system.nim");
					while (1) {
						NI TM_FYzz9bEDZQEsPJ4L9bzzDvVw_27;
						if (!(res_3 <= ((NI) 15))) goto LA30;
						nimln_(1988, "system.nim");
						i_6no7U3LksouOW9cjgQmL27w_2 = ((NI)chckRange(res_3, ((NI) 0), ((NI) 15)));
						{
							NI volatile res_4;
							j_gF9ar53guqMqheiPMKOEaAg_2 = 0;
							nimln_(1986, "system.nim");
							res_4 = ((NI) 0);
							{
								nimln_(1987, "system.nim");
								while (1) {
									tyArray_nHXaesL0DJZHyVS07ARPRA T34_;
									NimStringDesc* T35_;
									NimStringDesc* T36_;
									NimStringDesc* T37_;
									NimStringDesc* T38_;
									NI TM_FYzz9bEDZQEsPJ4L9bzzDvVw_26;
									if (!(res_4 <= ((NI) 10))) goto LA33;
									nimln_(1988, "system.nim");
									j_gF9ar53guqMqheiPMKOEaAg_2 = ((NI)chckRange(res_4, ((NI) 0), ((NI) 10)));
									nimln_(105, "smallpt.nim");
									memset((void*)T34_, 0, sizeof(T34_));
									T35_ = (NimStringDesc*)0;
									T36_ = (NimStringDesc*)0;
									T36_ = nimIntToStr(img_PW8HahrrKxSsH24BoBt9aFg[(i_6no7U3LksouOW9cjgQmL27w_2)- 0][(j_gF9ar53guqMqheiPMKOEaAg_2)- 0][(((NI) 0))- 0]);
									T37_ = (NimStringDesc*)0;
									T37_ = nimIntToStr(img_PW8HahrrKxSsH24BoBt9aFg[(i_6no7U3LksouOW9cjgQmL27w_2)- 0][(j_gF9ar53guqMqheiPMKOEaAg_2)- 0][(((NI) 1))- 0]);
									T38_ = (NimStringDesc*)0;
									T38_ = nimIntToStr(img_PW8HahrrKxSsH24BoBt9aFg[(i_6no7U3LksouOW9cjgQmL27w_2)- 0][(j_gF9ar53guqMqheiPMKOEaAg_2)- 0][(((NI) 2))- 0]);
									T35_ = rawNewString(T36_->Sup.len + T37_->Sup.len + T38_->Sup.len + 2);
appendString(T35_, T36_);
appendString(T35_, ((NimStringDesc*) &TM_FYzz9bEDZQEsPJ4L9bzzDvVw_25));
appendString(T35_, T37_);
appendString(T35_, ((NimStringDesc*) &TM_FYzz9bEDZQEsPJ4L9bzzDvVw_25));
appendString(T35_, T38_);
									T34_[0] = T35_;
									writeLine_rBQVO3cm3BhnA9aEFD7PG6Qsmallpt(f_y7t9aVv0a58PJGWzUFhhDSA, T34_, 1);
									nimln_(1989, "system.nim");
									TM_FYzz9bEDZQEsPJ4L9bzzDvVw_26 = addInt(res_4, ((NI) 1));
									res_4 = (NI)(TM_FYzz9bEDZQEsPJ4L9bzzDvVw_26);
								} LA33: ;
							}
						}
						TM_FYzz9bEDZQEsPJ4L9bzzDvVw_27 = addInt(res_3, ((NI) 1));
						res_3 = (NI)(TM_FYzz9bEDZQEsPJ4L9bzzDvVw_27);
					} LA30: ;
				}
			}
			popSafePoint();
		}
		else {
			popSafePoint();
			setFrame((TFrame*)&FR_);
		}
		{
			nimln_(97, "smallpt.nim");
			close_BWnr8V7RERYno9bIdPmw8Hw_2(f_y7t9aVv0a58PJGWzUFhhDSA);
			nimln_(98, "smallpt.nim");
			printf("%s\012", ((NimStringDesc*) &TM_FYzz9bEDZQEsPJ4L9bzzDvVw_28)? (((NimStringDesc*) &TM_FYzz9bEDZQEsPJ4L9bzzDvVw_28))->data:"nil");
			fflush(stdout);
		}
		if (TM_FYzz9bEDZQEsPJ4L9bzzDvVw_16.status != 0) reraiseException();
	}
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, smallptDatInit000)(void) {
NTI_9ce69c9a1NzlPVqY9aKHS79b5IQ_.size = sizeof(tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ);
NTI_9ce69c9a1NzlPVqY9aKHS79b5IQ_.kind = 16;
NTI_9ce69c9a1NzlPVqY9aKHS79b5IQ_.base = (&NTI_w9bl9a1ul9ctRJWiMl9cNnIMvg_);
NTI_9ce69c9a1NzlPVqY9aKHS79b5IQ_.flags = 3;
}

