/* Generated by Nim Compiler v0.17.2 */
/*   (c) 2017 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w  -I/usr/local/Cellar/nim/0.17.2/nim/lib -o /Users/nao/Documents/ray/nim-ray/nimcache/vector3.o /Users/nao/Documents/ray/nim-ray/nimcache/vector3.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <math.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef NF tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ[3];
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
N_NIMCALL(void, vinit_dVc3M7UzQrEdAg9bAichmaQ)(tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ Result);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(void, vinit_Hs4uSVvIYhJ3tkFQZ1TgAw)(NF a, NF b, NF c, tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ Result);
N_NIMCALL(NimStringDesc*, dollar__eonZb9cH9b5P9cxmaIhwpYeAQ)(tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ a);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size);
N_NIMCALL(NimStringDesc*, nimFloatToStr)(NF f);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
N_NIMCALL(void, plus__9czKeNUWXJd9b53pRTHJn9b9aA)(tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ left, tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ right, tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ Result);
N_NIMCALL(void, minus__9czKeNUWXJd9b53pRTHJn9b9aA_2)(tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ left, tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ right, tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ Result);
N_NIMCALL(void, star__lmxNqkFQDsnnY1SXJIgTcA)(NF left, tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ right, tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ Result);
N_NIMCALL(void, star__TzOM1KQPBfMv9ctpUW9bh8zA)(tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ left, NF right, tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ Result);
N_NIMCALL(NF, dot_0zy6PCF9bxu3Juwor6LKLLQ)(tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ left, tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ right);
N_NIMCALL(void, cross_9czKeNUWXJd9b53pRTHJn9b9aA_3)(tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ left, tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ right, tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ Result);
N_NIMCALL(void, mult_9czKeNUWXJd9b53pRTHJn9b9aA_4)(tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ left, tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ right, tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ Result);
N_NIMCALL(NF, norm_tgL15ccYkgdkAASAbX7SQw)(tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ this_0);
N_NIMCALL(void, normalize_am9blMcNk854iovcwUojw9aw)(tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ this_0, tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ Result);
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TNimType NTI_w9bl9a1ul9ctRJWiMl9cNnIMvg_;
TNimType NTI_9ce69c9a1NzlPVqY9aKHS79b5IQ_;
NIM_CONST tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ TM_cXCsxZhCatJBB6eSB9cDHvA_2 = {0.0,
0.0,
0.0}
;
STRING_LITERAL(TM_cXCsxZhCatJBB6eSB9cDHvA_3, "[", 1);
STRING_LITERAL(TM_cXCsxZhCatJBB6eSB9cDHvA_4, ", ", 2);
STRING_LITERAL(TM_cXCsxZhCatJBB6eSB9cDHvA_5, "]", 1);

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_NIMCALL(void, vinit_dVc3M7UzQrEdAg9bAichmaQ)(tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ Result) {
	nimfr_("vinit", "vector3.nim");
	nimln_(7, "vector3.nim");
	memcpy((void*)Result, (NIM_CONST void*)TM_cXCsxZhCatJBB6eSB9cDHvA_2, sizeof(tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ));
	popFrame();
}

N_NIMCALL(void, vinit_Hs4uSVvIYhJ3tkFQZ1TgAw)(NF a, NF b, NF c, tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ Result) {
	nimfr_("vinit", "vector3.nim");
	nimln_(10, "vector3.nim");
	Result[0] = a;
	Result[1] = b;
	Result[2] = c;
	popFrame();
}

static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	copyMem_E1xtACub5WcDa3vbrIXbwgsystem(((void*) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
	(*dest).Sup.len += (*src).Sup.len;
}

N_NIMCALL(NimStringDesc*, dollar__eonZb9cH9b5P9cxmaIhwpYeAQ)(tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ a) {
	NimStringDesc* result;
	NimStringDesc* T1_;
	NimStringDesc* T2_;
	NimStringDesc* T3_;
	NimStringDesc* T4_;
	nimfr_("$", "vector3.nim");
	result = (NimStringDesc*)0;
	nimln_(13, "vector3.nim");
	T1_ = (NimStringDesc*)0;
	T2_ = (NimStringDesc*)0;
	T2_ = nimFloatToStr(a[(((NI) 0))- 0]);
	T3_ = (NimStringDesc*)0;
	T3_ = nimFloatToStr(a[(((NI) 1))- 0]);
	T4_ = (NimStringDesc*)0;
	T4_ = nimFloatToStr(a[(((NI) 2))- 0]);
	T1_ = rawNewString(T2_->Sup.len + T3_->Sup.len + T4_->Sup.len + 6);
appendString(T1_, ((NimStringDesc*) &TM_cXCsxZhCatJBB6eSB9cDHvA_3));
appendString(T1_, T2_);
appendString(T1_, ((NimStringDesc*) &TM_cXCsxZhCatJBB6eSB9cDHvA_4));
appendString(T1_, T3_);
appendString(T1_, ((NimStringDesc*) &TM_cXCsxZhCatJBB6eSB9cDHvA_4));
appendString(T1_, T4_);
appendString(T1_, ((NimStringDesc*) &TM_cXCsxZhCatJBB6eSB9cDHvA_5));
	result = T1_;
	popFrame();
	return result;
}

N_NIMCALL(void, plus__9czKeNUWXJd9b53pRTHJn9b9aA)(tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ left, tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ right, tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ Result) {
	nimfr_("+", "vector3.nim");
	nimln_(16, "vector3.nim");
	Result[0] = ((NF)(left[(((NI) 0))- 0]) + (NF)(right[(((NI) 0))- 0]));
	Result[1] = ((NF)(left[(((NI) 1))- 0]) + (NF)(right[(((NI) 1))- 0]));
	Result[2] = ((NF)(left[(((NI) 2))- 0]) + (NF)(right[(((NI) 2))- 0]));
	popFrame();
}

N_NIMCALL(void, minus__9czKeNUWXJd9b53pRTHJn9b9aA_2)(tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ left, tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ right, tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ Result) {
	nimfr_("-", "vector3.nim");
	nimln_(19, "vector3.nim");
	Result[0] = ((NF)(left[(((NI) 0))- 0]) - (NF)(right[(((NI) 0))- 0]));
	Result[1] = ((NF)(left[(((NI) 1))- 0]) - (NF)(right[(((NI) 1))- 0]));
	Result[2] = ((NF)(left[(((NI) 2))- 0]) - (NF)(right[(((NI) 2))- 0]));
	popFrame();
}

N_NIMCALL(void, star__lmxNqkFQDsnnY1SXJIgTcA)(NF left, tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ right, tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ Result) {
	nimfr_("*", "vector3.nim");
	nimln_(22, "vector3.nim");
	Result[0] = ((NF)(left) * (NF)(right[(((NI) 0))- 0]));
	Result[1] = ((NF)(left) * (NF)(right[(((NI) 1))- 0]));
	Result[2] = ((NF)(left) * (NF)(right[(((NI) 2))- 0]));
	popFrame();
}

N_NIMCALL(void, star__TzOM1KQPBfMv9ctpUW9bh8zA)(tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ left, NF right, tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ Result) {
	nimfr_("*", "vector3.nim");
	nimln_(25, "vector3.nim");
	Result[0] = ((NF)(left[(((NI) 0))- 0]) * (NF)(right));
	Result[1] = ((NF)(left[(((NI) 1))- 0]) * (NF)(right));
	Result[2] = ((NF)(left[(((NI) 2))- 0]) * (NF)(right));
	popFrame();
}

N_NIMCALL(NF, dot_0zy6PCF9bxu3Juwor6LKLLQ)(tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ left, tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ right) {
	NF result;
	nimfr_("dot", "vector3.nim");
	result = (NF)0;
	nimln_(28, "vector3.nim");
	result = ((NF)(((NF)(((NF)(left[(((NI) 0))- 0]) * (NF)(right[(((NI) 0))- 0]))) + (NF)(((NF)(left[(((NI) 1))- 0]) * (NF)(right[(((NI) 1))- 0]))))) + (NF)(((NF)(left[(((NI) 2))- 0]) * (NF)(right[(((NI) 2))- 0]))));
	popFrame();
	return result;
}

N_NIMCALL(void, cross_9czKeNUWXJd9b53pRTHJn9b9aA_3)(tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ left, tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ right, tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ Result) {
	nimfr_("cross", "vector3.nim");
	nimln_(31, "vector3.nim");
	Result[0] = ((NF)(((NF)(left[(((NI) 1))- 0]) * (NF)(right[(((NI) 2))- 0]))) - (NF)(((NF)(right[(((NI) 2))- 0]) * (NF)(left[(((NI) 1))- 0]))));
	Result[1] = ((NF)(((NF)(left[(((NI) 2))- 0]) * (NF)(right[(((NI) 0))- 0]))) - (NF)(((NF)(right[(((NI) 0))- 0]) * (NF)(left[(((NI) 2))- 0]))));
	Result[2] = ((NF)(((NF)(left[(((NI) 0))- 0]) * (NF)(right[(((NI) 1))- 0]))) - (NF)(((NF)(right[(((NI) 1))- 0]) * (NF)(left[(((NI) 0))- 0]))));
	popFrame();
}

N_NIMCALL(void, mult_9czKeNUWXJd9b53pRTHJn9b9aA_4)(tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ left, tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ right, tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ Result) {
	nimfr_("mult", "vector3.nim");
	nimln_(34, "vector3.nim");
	Result[0] = ((NF)(left[(((NI) 0))- 0]) * (NF)(right[(((NI) 0))- 0]));
	Result[1] = ((NF)(left[(((NI) 1))- 0]) * (NF)(right[(((NI) 1))- 0]));
	Result[2] = ((NF)(left[(((NI) 2))- 0]) * (NF)(right[(((NI) 2))- 0]));
	popFrame();
}

N_NIMCALL(NF, norm_tgL15ccYkgdkAASAbX7SQw)(tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ this_0) {
	NF result;
	NF T1_;
	nimfr_("norm", "vector3.nim");
	result = (NF)0;
	nimln_(37, "vector3.nim");
	T1_ = (NF)0;
	T1_ = dot_0zy6PCF9bxu3Juwor6LKLLQ(this_0, this_0);
	result = sqrt(T1_);
	popFrame();
	return result;
}

N_NIMCALL(void, normalize_am9blMcNk854iovcwUojw9aw)(tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ this_0, tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ Result) {
	NF T1_;
	tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ T2_;
	nimfr_("normalize", "vector3.nim");
	nimln_(40, "vector3.nim");
	T1_ = (NF)0;
	T1_ = norm_tgL15ccYkgdkAASAbX7SQw(this_0);
	memset((void*)T2_, 0, sizeof(T2_));
	star__TzOM1KQPBfMv9ctpUW9bh8zA(this_0, ((NF)(1.0000000000000000e+00) / (NF)(T1_)), T2_);
	memcpy((void*)Result, (NIM_CONST void*)T2_, sizeof(tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ));
	popFrame();
}
NIM_EXTERNC N_NOINLINE(void, unknown_vector3Init000)(void) {
	nimfr_("vector3", "vector3.nim");
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, unknown_vector3DatInit000)(void) {
NTI_9ce69c9a1NzlPVqY9aKHS79b5IQ_.size = sizeof(tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ);
NTI_9ce69c9a1NzlPVqY9aKHS79b5IQ_.kind = 16;
NTI_9ce69c9a1NzlPVqY9aKHS79b5IQ_.base = (&NTI_w9bl9a1ul9ctRJWiMl9cNnIMvg_);
NTI_9ce69c9a1NzlPVqY9aKHS79b5IQ_.flags = 3;
}

